import test from 'node:test';
import assert from 'node:assert/strict';
import { calculatePricing, pricingScenarios } from '../lib/pricing/calculator';
import { decideBidFit, normalizeComplianceState, scoreBidReadiness, scoreQualityLabel } from '../lib/decision/score';
import { JSON_SCHEMA, validateAnalysis } from '../lib/ai/schema';
import { chunkSolicitationPackage, analyzeSolicitationText, isDirectPdfUnsupportedError, prepareExtractionText } from '../lib/ai/analyze';
import { validatePdfFile } from '../lib/documents/validate';
import { demoAnalysis } from '../lib/demo';
const base = JSON.parse(JSON.stringify(demoAnalysis));
base.analysisVersion='2.2.0'; delete base.modelUsed; delete base.requestId; delete base.generatedAt;
for (const key of Object.keys(base.summary)) { base.summary[key].evidence ||= ''; base.summary[key].documentName ||= 'demo.pdf'; base.summary[key].pageNumber ??= null; }
for (const field of ['solicitationNumber','department','issuingOffice','solicitationType','contractType','issueDate','questionsDeadline','preBidConference','siteVisit','timezone','periodOfPerformance','setAside','NAICS','PSC','placeOfPerformance','deliveryLocations','portal','email','physicalAddress','requiredEmailSubject','attachmentSizeLimit','numberOfCopies','filenameConventions','awardBasis','evaluationFactors','priceEvaluationMethod','requiredForms','signatures','addendaAcknowledgment','registrations','licenses','certifications','insurance','bonding','samples','warranty','technicalDocumentation','countryOfOriginRequirements','paymentTerms','priceValidity','FOBTerms','freightRequirements','installation','training']) base.summary[field]={value:'Not Found',confidence:'Needs Clarification',status:'Not Found',evidence:'',documentName:'',pageNumber:null};
for (const c of base.complianceMatrix) { c.documentName='demo.pdf'; c.evidence ||= 'demo evidence'; c.pageNumber ??= null; }
for (const c of base.checklist) { c.priority ||= c.riskLevel; c.blocking=!!c.blocking; c.sourceRequirement ||= c.task; }
base.subScores={technicalFit:{score:70,confidence:'Medium',reasoning:'ok'},commercialFit:{score:70,confidence:'Medium',reasoning:'ok'},complianceReadiness:{score:60,confidence:'Medium',reasoning:'ok'},deliveryFeasibility:{score:60,confidence:'Medium',reasoning:'ok'},pastPerformanceFit:{score:50,confidence:'Needs Clarification',reasoning:'unknown'},supplierReadiness:{score:50,confidence:'Needs Clarification',reasoning:'unknown'},deadlineFeasibility:{score:80,confidence:'Medium',reasoning:'ok'}};
test('pricing calculation outputs known margin markup and break-even',()=>{const r=calculatePricing({productCost:100,freight:10,otherRiskCost:0,targetMargin:20},2); assert.equal(r.landedUnitCost,110); assert.equal(r.breakEvenPrice,110); assert.equal(Math.round(r.recommendedUnitBidPrice*100)/100,137.5); assert.equal(Math.round(r.grossMargin*10)/10,20); assert.equal(Math.round(r.markup*10)/10,25); assert.equal(r.extendedBidAmount,275);});
test('pricing scenarios produce aggressive target conservative order',()=>{const s=pricingScenarios({productCost:100,freight:0,otherRiskCost:0,targetMargin:20},1); assert(s.Aggressive.recommendedUnitBidPrice < s.Target.recommendedUnitBidPrice); assert(s.Target.recommendedUnitBidPrice < s.Conservative.recommendedUnitBidPrice);});
test('decision hard stop yields No Bid',()=>assert.equal(decideBidFit({hardStops:['Deadline passed']}),'No Bid'));
test('decision unknown mandatory capability yields Needs Clarification',()=>assert.equal(decideBidFit({unknownMandatoryCapabilities:['Insurance limits unknown']}),'Needs Clarification'));
test('decision no hard stop does not automatically become No Bid',()=>assert.notEqual(decideBidFit({technicalFit:30,commercialFit:30}),'No Bid'));
test('decision engine returns transparent scoring',()=>{const r=scoreBidReadiness({technicalFit:90,commercialFit:80,complianceReadiness:70,deliveryFeasibility:80,pastPerformanceFit:60,supplierReadiness:70,deadlineFeasibility:90}); assert.equal(r.recommendation,'Bid'); assert(r.opportunityScore.score>0); assert.equal(Object.keys(r.subScores).length,7);});
test('schema validation accepts complete structured output and stamps metadata',()=>{const out=validateAnalysis(base,{modelUsed:'test-model',requestId:'req-1'}); assert.equal(out.modelUsed,'test-model'); assert.equal(out.requestId,'req-1');});
test('schema validation rejects malformed critical output',()=>assert.throws(()=>validateAnalysis({recommendation:'Bid'}, {modelUsed:'m',requestId:'r'}),/Structured analysis validation failed/));
test('normalization does not hide structurally invalid AI responses',()=>{const bad={...base,summary:{}}; assert.throws(()=>validateAnalysis(bad,{modelUsed:'m',requestId:'r'}),/summary\.bidNumber/);});
test('invalid PDF magic bytes are rejected',async()=>{const f=new File([new Uint8Array([1,2,3])],'bad.pdf',{type:'application/pdf'}); await assert.rejects(()=>validatePdfFile(f),/not a valid PDF/);});
test('oversized PDFs are rejected',async()=>{const f=new File([new Blob([new Uint8Array(26*1024*1024)])],'big.pdf',{type:'application/pdf'}); await assert.rejects(()=>validatePdfFile(f),/25 MB/);});
test('empty PDFs are rejected',async()=>{const f=new File([],'empty.pdf',{type:'application/pdf'}); await assert.rejects(()=>validatePdfFile(f),/empty/);});
test('long package is chunked without dropping tail content',()=>{const tail='TAIL_DEADLINE_REQUIREMENT'; const chunks=chunkSolicitationPackage('A'.repeat(46000)+tail,45000); assert(chunks.length>1); assert(chunks.join('').includes(tail));});
test('single extraction compaction preserves document tail without repeated AI chunk calls',()=>{const tail='TAIL_DEADLINE_REQUIREMENT'; const compacted=prepareExtractionText(`[test.pdf page 1] ${'A'.repeat(200000)} ${tail}`,120000); assert(compacted.length<=120000); assert(compacted.includes(tail)); assert(compacted.includes('Section compacted'));});
test('real analysis code path cannot return demoAnalysis when API key missing',async()=>{const old=process.env.OPENAI_API_KEY; delete process.env.OPENAI_API_KEY; await assert.rejects(()=>analyzeSolicitationText('real text','req'),/OpenAI is not configured/); process.env.OPENAI_API_KEY=old;});

test('strict JSON schema requires every object property recursively',()=>{const missing:string[]=[]; function visit(schema:any,path:string){ if(!schema||typeof schema!=='object')return; const types=Array.isArray(schema.type)?schema.type:[schema.type]; if(types.includes('object')&&schema.properties){ const required=new Set(schema.required||[]); for(const key of Object.keys(schema.properties)){ if(!required.has(key)) missing.push(`${path}.${key}`); visit(schema.properties[key],`${path}.${key}`); } } if(schema.items) visit(schema.items,`${path}[]`); } visit(JSON_SCHEMA.schema,'schema'); assert.deepEqual(missing,[]);});
test('direct scanned-PDF classifier only treats actual file-read support failures as OCR unsupported',()=>{assert.equal(isDirectPdfUnsupportedError(new Error('file inputs are not supported by this model')),true); assert.equal(isDirectPdfUnsupportedError(new Error('401 invalid API key')),false); assert.equal(isDirectPdfUnsupportedError(new Error('Structured analysis validation failed: missing summary')),false); assert.equal(isDirectPdfUnsupportedError(new Error('500 temporary service unavailable')),false);});
test('preview aliases canonicalize into canonical summary fields and remove snake_case keys',()=>{const response=JSON.parse(JSON.stringify(base)); response.summary.agency={value:'Not Found',confidence:'Needs Clarification',status:'Not Found',evidence:'',documentName:'',pageNumber:null}; response.summary.dueDateTime={value:'Not Found',confidence:'Needs Clarification',status:'Not Found',evidence:'',documentName:'',pageNumber:null}; response.summary.issueDate={value:'Not Found',confidence:'Needs Clarification',status:'Not Found',evidence:'',documentName:'',pageNumber:null}; response.summary.awardBasis={value:'Not Found',confidence:'Needs Clarification',status:'Not Found',evidence:'',documentName:'',pageNumber:null}; response.summary.issuing_agency={value:'Department of Test',confidence:'High',status:'Fact',evidence:'Agency line',documentName:'test.pdf',pageNumber:null}; response.summary.bid_due={value:'07/23/2026 at 11:00 AM CT',confidence:'High',status:'Fact',evidence:'Bid due line',documentName:'test.pdf',pageNumber:null}; response.summary.issue_date={value:'07/01/2026',confidence:'High',status:'Fact',evidence:'Issued line',documentName:'test.pdf',pageNumber:null}; response.summary.award_basis={value:'Lowest responsive responsible bidder',confidence:'High',status:'Fact',evidence:'Award line',documentName:'test.pdf',pageNumber:null}; const out=validateAnalysis(response,{modelUsed:'m',requestId:'r'}); assert.equal(out.summary.agency.value,'Department of Test'); assert.equal(out.summary.dueDateTime.value,'07/23/2026 at 11:00 AM CT'); assert.equal(out.summary.issueDate.value,'07/01/2026'); assert.equal(out.summary.awardBasis.value,'Lowest responsive responsible bidder'); assert(!('issuing_agency' in out.summary)); assert(!('bid_due' in out.summary));});
test('unknown root and summary properties are rejected',()=>{const root={...base,unexpected:'nope'}; assert.throws(()=>validateAnalysis(root,{modelUsed:'m',requestId:'r'}),/unexpected is not allowed/); const summary=JSON.parse(JSON.stringify(base)); summary.summary.raw_snake='bad'; assert.throws(()=>validateAnalysis(summary,{modelUsed:'m',requestId:'r'}),/summary\.raw_snake is not allowed/);});
test('semantic validation rejects Fact with empty or Not Found value',()=>{const empty=JSON.parse(JSON.stringify(base)); empty.summary.agency={...empty.summary.agency,status:'Fact',value:''}; assert.throws(()=>validateAnalysis(empty,{modelUsed:'m',requestId:'r'}),/Fact requires a meaningful value/); const notFound=JSON.parse(JSON.stringify(base)); notFound.summary.agency={...notFound.summary.agency,status:'Fact',value:'Not Found'}; assert.throws(()=>validateAnalysis(notFound,{modelUsed:'m',requestId:'r'}),/Fact requires a meaningful value/);});
test('Needs Clarification with no gates or questions is rejected',()=>{const bad=JSON.parse(JSON.stringify(base)); bad.recommendation='Needs Clarification'; bad.clarificationGates=[]; bad.clarificationQuestions=[]; assert.throws(()=>validateAnalysis(bad,{modelUsed:'m',requestId:'r'}),/Needs Clarification requires/);});
test('unexplained zero opportunity score is rejected',()=>{const bad=JSON.parse(JSON.stringify(base)); bad.opportunityScore={score:0,confidence:'High',reasoning:''}; assert.throws(()=>validateAnalysis(bad,{modelUsed:'m',requestId:'r'}),/opportunityScore\.reasoning required/);});
test('deterministic scoring returns identical scores and recommendation for identical normalized inputs',()=>{const a=validateAnalysis(JSON.parse(JSON.stringify(base)),{modelUsed:'m',requestId:'r1'}); const b=validateAnalysis(JSON.parse(JSON.stringify(base)),{modelUsed:'m',requestId:'r2'}); assert.deepEqual(a.subScores,b.subScores); assert.equal(a.opportunityScore.score,b.opportunityScore.score); assert.equal(a.recommendation,b.recommendation);});
test('unknown capability is scored differently from confirmed mandatory failure',()=>{const unknown=JSON.parse(JSON.stringify(base)); unknown.clarificationGates=['Confirm insurance capability']; unknown.complianceMatrix[0].status='Unknown'; const u=validateAnalysis(unknown,{modelUsed:'m',requestId:'u'}); assert.equal(u.recommendation,'Needs Clarification'); const failed=JSON.parse(JSON.stringify(base)); failed.complianceMatrix[0].status='Not Compliant'; failed.complianceMatrix[0].mandatory=true; const f=validateAnalysis(failed,{modelUsed:'m',requestId:'f'}); assert.equal(f.recommendation,'No Bid'); assert(f.opportunityScore.score<u.opportunityScore.score);});
test('ordinary solicitation rules become disqualification risks not active hard stops',()=>{const sample=JSON.parse(JSON.stringify(base)); sample.hardStops=['Late bids are rejected','Hard copies are not accepted','Confirmed bidder cannot meet mandatory PIV specification']; const out=validateAnalysis(sample,{modelUsed:'m',requestId:'h'}); assert.deepEqual(out.hardStops,['Confirmed bidder cannot meet mandatory PIV specification']); assert(out.disqualificationRisks.includes('Late bids are rejected')); assert(out.disqualificationRisks.includes('Hard copies are not accepted'));});
test('compliance owner routing does not assign buyer to internal tasks',()=>{const sample=JSON.parse(JSON.stringify(base)); sample.complianceMatrix[0].owner='Buyer / Contracting Officer'; sample.complianceMatrix[0].category='Insurance'; const out=validateAnalysis(sample,{modelUsed:'m',requestId:'o'}); assert.equal(out.complianceMatrix.find((c:any)=>c.id==='INSURANCE_REQUIREMENTS')?.owner,'Legal/Compliance');});
test('unknown fields do not randomly change deterministic score',()=>{const sample=JSON.parse(JSON.stringify(base)); sample.summary.insurance={value:'Not Found',confidence:'Needs Clarification',status:'Not Found',evidence:'',documentName:'',pageNumber:null}; const scores=new Set(Array.from({length:5},(_,i)=>validateAnalysis(JSON.parse(JSON.stringify(sample)),{modelUsed:'m',requestId:`s${i}`}).opportunityScore.score)); assert.equal(scores.size,1);});

test('model-generated line fitScore changes do not change deterministic final scores',()=>{const a=JSON.parse(JSON.stringify(base)); const b=JSON.parse(JSON.stringify(base)); a.lineItems[0].fitScore=0; b.lineItems[0].fitScore=10; const outA=validateAnalysis(a,{modelUsed:'m',requestId:'la'}); const outB=validateAnalysis(b,{modelUsed:'m',requestId:'lb'}); assert.equal(outA.subScores.technicalFit.score,outB.subScores.technicalFit.score); assert.equal(outA.opportunityScore.score,outB.opportunityScore.score);});
test('canonical compliance state normalization is stable for equivalent unknowns',()=>{assert.equal(normalizeComplianceState({...base.complianceMatrix[0],status:'Unknown'}),'unknown'); assert.equal(normalizeComplianceState({...base.complianceMatrix[0],status:'Needs Clarification'}),'unknown'); assert.equal(normalizeComplianceState({...base.complianceMatrix[0],status:'Not Compliant'}),'noncompliant'); assert.equal(normalizeComplianceState({...base.complianceMatrix[0],status:'Compliant'}),'confirmed');});
test('score range labels are semantically correct',()=>{assert.equal(scoreQualityLabel(0),'Low'); assert.equal(scoreQualityLabel(39),'Low'); assert.equal(scoreQualityLabel(40),'Medium'); assert.equal(scoreQualityLabel(69),'Medium'); assert.equal(scoreQualityLabel(70),'Good'); assert.equal(scoreQualityLabel(84),'Good'); assert.equal(scoreQualityLabel(85),'High'); assert.equal(scoreQualityLabel(100),'High');});

test('empty bidder profile readiness statements create zero active hard stops',()=>{const sample=JSON.parse(JSON.stringify(base)); sample.hardStops=['Do not submit unless LSU Workday supplier enrollment and W-9/W-8 documentation can be completed or confirmed.']; sample.clarificationGates=['Confirm LSU Workday enrollment and W-9/W-8 readiness']; const out=validateAnalysis(sample,{modelUsed:'m',requestId:'empty-profile'}); assert.deepEqual(out.hardStops,[]); assert(out.disqualificationRisks.includes('Do not submit unless LSU Workday supplier enrollment and W-9/W-8 documentation can be completed or confirmed.')); assert.equal(out.recommendation,'Needs Clarification'); assert(out.opportunityScore.score>35);});
test('unknown bidder capabilities are not active hard stops',()=>{for(const text of ['Unknown Workday enrollment status','Unknown W-9/W-8 status','Unknown insurance capability','Unknown technical capability','Needs clarification on delivery capability']){const sample=JSON.parse(JSON.stringify(base)); sample.hardStops=[text]; sample.clarificationGates=[text]; const out=validateAnalysis(sample,{modelUsed:'m',requestId:text}); assert.deepEqual(out.hardStops,[]); assert.equal(out.recommendation,'Needs Clarification');}});
test('confirmed inability to complete required registration is active hard stop',()=>{const sample=JSON.parse(JSON.stringify(base)); sample.hardStops=['Confirmed bidder cannot complete mandatory Workday registration before the required deadline']; const out=validateAnalysis(sample,{modelUsed:'m',requestId:'registration-stop'}); assert.deepEqual(out.hardStops,['Confirmed bidder cannot complete mandatory Workday registration before the required deadline']); assert.equal(out.recommendation,'No Bid'); assert(out.opportunityScore.score<=35);});
test('confirmed mandatory technical noncompliance is active hard stop',()=>{const sample=JSON.parse(JSON.stringify(base)); sample.hardStops=['Confirmed mandatory technical noncompliance with PIV specification']; const out=validateAnalysis(sample,{modelUsed:'m',requestId:'technical-stop'}); assert.deepEqual(out.hardStops,['Confirmed mandatory technical noncompliance with PIV specification']); assert.equal(out.recommendation,'No Bid');});
test('no active hard stops with unresolved unknowns means Needs Review not No-Go',()=>{const sample=JSON.parse(JSON.stringify(base)); sample.hardStops=['Failure to provide W-9/W-8 may result in rejection']; sample.clarificationGates=['Confirm W-9/W-8 readiness']; const out=validateAnalysis(sample,{modelUsed:'m',requestId:'needs-review'}); assert.deepEqual(out.hardStops,[]); assert.equal(out.recommendation,'Needs Clarification');});
test('equivalent Workday registration wording normalizes to SUPPLIER_REGISTRATION',()=>{const a=JSON.parse(JSON.stringify(base)); const b=JSON.parse(JSON.stringify(base)); a.complianceMatrix=[{...a.complianceMatrix[0],requirement:'Supplier must enroll in LSU Workday.',category:'Registration',status:'Unknown'}]; b.complianceMatrix=[{...b.complianceMatrix[0],requirement:'LSU Workday supplier registration is required.',category:'Registration',status:'Needs Clarification'}]; const outA=validateAnalysis(a,{modelUsed:'m',requestId:'wa'}); const outB=validateAnalysis(b,{modelUsed:'m',requestId:'wb'}); assert(outA.canonicalRequirements?.some((r:any)=>r.canonicalKey==='SUPPLIER_REGISTRATION')); assert(outB.canonicalRequirements?.some((r:any)=>r.canonicalKey==='SUPPLIER_REGISTRATION')); assert.equal(outA.canonicalRequirements?.length,outB.canonicalRequirements?.length); assert.equal(outA.opportunityScore.score,outB.opportunityScore.score); assert.equal(outA.recommendation,outB.recommendation);});
test('duplicate requirements dedupe to one canonical requirement and one clarification',()=>{const sample=JSON.parse(JSON.stringify(base)); sample.complianceMatrix=[{...sample.complianceMatrix[0],id:'a',requirement:'Supplier must enroll in LSU Workday.',category:'Registration',status:'Unknown'},{...sample.complianceMatrix[0],id:'b',requirement:'Workday supplier enrollment required.',category:'Registration',status:'Needs Clarification'}]; sample.mandatoryRequirements=['LSU Workday registration required']; sample.clarificationQuestions=[]; const out=validateAnalysis(sample,{modelUsed:'m',requestId:'dedupe'}); assert.equal(out.canonicalRequirements?.filter(r=>r.canonicalKey==='SUPPLIER_REGISTRATION').length,1); assert.equal(out.complianceMatrix.filter(c=>c.id==='SUPPLIER_REGISTRATION').length,1); assert.equal(out.clarificationQuestions.filter(q=>q.relatedRequirement==='SUPPLIER_REGISTRATION').length,1);});
test('stable canonical IDs drive same requirement counts and scores despite wording',()=>{const a=JSON.parse(JSON.stringify(base)); const b=JSON.parse(JSON.stringify(base)); a.complianceMatrix=[{...a.complianceMatrix[0],requirement:'W-9/W-8 required',category:'Administrative',status:'Unknown'},{...a.complianceMatrix[0],requirement:'Supplier must enroll in LSU Workday.',category:'Registration',status:'Unknown'}]; b.complianceMatrix=[{...b.complianceMatrix[0],requirement:'Tax documentation required',category:'Administrative',status:'Needs Clarification'},{...b.complianceMatrix[0],requirement:'LSU Workday supplier registration is required.',category:'Registration',status:'Needs Clarification'}]; const outA=validateAnalysis(a,{modelUsed:'m',requestId:'sa'}); const outB=validateAnalysis(b,{modelUsed:'m',requestId:'sb'}); assert.deepEqual(outA.canonicalRequirements?.map(r=>r.canonicalKey),outB.canonicalRequirements?.map(r=>r.canonicalKey)); assert.equal(outA.canonicalRequirements?.length,outB.canonicalRequirements?.length); assert.deepEqual(outA.subScores,outB.subScores); assert.equal(outA.opportunityScore.score,outB.opportunityScore.score);});
test('compliance matrix uses stable canonical IDs',()=>{const sample=JSON.parse(JSON.stringify(base)); sample.complianceMatrix=[{...sample.complianceMatrix[0],id:'freeform-123',requirement:'W-9/W-8 required',category:'Administrative',status:'Unknown'}]; const out=validateAnalysis(sample,{modelUsed:'m',requestId:'matrix-id'}); assert(out.complianceMatrix.some((c:any)=>c.id==='TAX_DOCUMENTATION'));});
