import { NextResponse } from 'next/server';
import { analyzeSolicitationPdfFiles, analyzeSolicitationText, AnalysisError } from '@/lib/analyze';
import { buildPackageText, extractPdfText } from '@/lib/documents/extract';
import { MAX_FILE_COUNT, validatePdfFile } from '@/lib/documents/validate';
export const runtime='nodejs';
export const maxDuration=180;
const buckets=new Map<string,{count:number;reset:number}>();
function rateLimit(ip:string){const now=Date.now(); const b=buckets.get(ip); if(!b||b.reset<now){buckets.set(ip,{count:1,reset:now+60_000});return false} b.count++; return b.count>10}
function logTiming(requestId:string,stage:string,started:number,extra=''){console.info(`[bidpilot:${requestId}] ${stage} ${Date.now()-started}ms${extra?` ${extra}`:''}`)}
async function timed<T>(requestId:string,stage:string,fn:()=>Promise<T>){const started=Date.now(); try{return await fn()}finally{logTiming(requestId,stage,started)}}
export async function POST(request:Request){const requestId=crypto.randomUUID(); try{ const ip=request.headers.get('x-forwarded-for')?.split(',')[0]?.trim()||'local'; if(rateLimit(ip)) return NextResponse.json({error:'Too many analysis requests. Please wait and try again.',requestId},{status:429}); const form=await timed(requestId,'request.form_data',()=>request.formData()); const files=form.getAll('file').filter((f):f is File=>f instanceof File); if(!files.length) return NextResponse.json({error:'Upload one or more PDF files.',requestId},{status:400}); if(files.length>MAX_FILE_COUNT) return NextResponse.json({error:`Upload up to ${MAX_FILE_COUNT} PDF files per analysis.`,requestId},{status:400}); const docs=[]; const pdfFiles=[]; for(const file of files){const name=await timed(requestId,'pdf.validation',()=>validatePdfFile(file)); const buffer=Buffer.from(await timed(requestId,'pdf.buffer_read',()=>file.arrayBuffer())); pdfFiles.push({name,buffer}); try{docs.push(await timed(requestId,'pdf.text_extraction',()=>extractPdfText(buffer,name)));}catch(e){ if(e instanceof Error && e.message.includes('No selectable text')) continue; throw e; }} const analysis=await Promise.race([docs.length?analyzeSolicitationText(buildPackageText(docs),requestId):analyzeSolicitationPdfFiles(pdfFiles,requestId),new Promise((_,rej)=>setTimeout(()=>rej(new AnalysisError('Analysis exceeded the application request timeout before analysis completed. Please retry; if this repeats, contact support with the request ID.',504)),170000))]) ; logTiming(requestId,'analysis.complete',Date.now()); return NextResponse.json(analysis,{headers:{'X-Request-Id':requestId}}); }catch(e){const status=e instanceof AnalysisError?e.status: e instanceof Error && e.message.includes('PDF')?400:500; return NextResponse.json({error:e instanceof Error?e.message:'Analysis failed safely.',requestId},{status,headers:{'X-Request-Id':requestId}})} }
