import OpenAI from 'openai';
import { validateAnalysis, JSON_SCHEMA } from './schema';
import { SYSTEM_PROMPT, buildRepairPrompt, buildUserPrompt } from './prompts';
import type { BidAnalysis } from '@/lib/types';
export class AnalysisError extends Error { status=500; constructor(message:string,status=500){super(message);this.status=status} }
const MAX_CHUNK_CHARS=45000;
const MAX_EXTRACTION_TEXT_CHARS=120000;
const OPENAI_EXTRACTION_TIMEOUT_MS=105000;
function logTiming(requestId:string,stage:string,started:number,extra=''){if(process.env.NODE_ENV!=='test') console.info(`[bidpilot:${requestId}] ${stage} ${Date.now()-started}ms${extra?` ${extra}`:''}`)}
async function timed<T>(requestId:string,stage:string,fn:()=>Promise<T>){const started=Date.now(); try{return await fn()}finally{logTiming(requestId,stage,started)}}
export async function analyzeSolicitationText(text:string, requestId:string=crypto.randomUUID()): Promise<BidAnalysis>{
 if(!process.env.OPENAI_API_KEY) throw new AnalysisError('OpenAI is not configured. Add OPENAI_API_KEY before analyzing real solicitations.',500);
 if(!text.trim()) throw new AnalysisError('No analyzable solicitation text was found. Upload a searchable PDF or OCR copy.',422);
 const model=process.env.OPENAI_MODEL||'gpt-5.6'; const client=new OpenAI({apiKey:process.env.OPENAI_API_KEY});
 try{ const prepared=timedSync(requestId,'document.compaction',()=>prepareExtractionText(text));
  return await timed(requestId,'openai.extraction_total',()=>requestStructuredAnalysis(client,model,buildUserPrompt(prepared),requestId));
 } catch(e){ if(e instanceof AnalysisError) throw e; const message=e instanceof Error?e.message:String(e); logTiming(requestId,`analysis.error type=${e instanceof Error?e.name:typeof e} message=${message.slice(0,180)}`,Date.now()); throw new AnalysisError(message.startsWith('Structured analysis validation failed') ? message : `Solicitation analysis failed safely during structured extraction or deterministic processing. No demo data was returned. Request ID: ${requestId}.`,502); }
}
function timedSync<T>(requestId:string,stage:string,fn:()=>T){const started=Date.now(); try{return fn()}finally{logTiming(requestId,stage,started)}}
async function requestStructuredAnalysis(client:OpenAI, model:string, prompt:string, requestId:string):Promise<BidAnalysis>{ const raw=await timed(requestId,'openai.extraction_request',()=>requestRawStructured(client,model,prompt)); try{return timedSync(requestId,'parse.normalize.score',()=>validateRawAnalysis(raw,model,requestId))}catch(error){ if(!(error instanceof Error)||!error.message.startsWith('Structured analysis validation failed')) throw error; const repaired=await timed(requestId,'openai.repair_request',()=>requestRawStructured(client,model,buildRepairPrompt(raw,error.message))); return timedSync(requestId,'parse.normalize.score.repair',()=>validateRawAnalysis(repaired,model,requestId))} }
async function requestRawStructured(client:OpenAI,model:string,prompt:string){const controller=new AbortController(); const timer=setTimeout(()=>controller.abort(),OPENAI_EXTRACTION_TIMEOUT_MS); try{const res:any=await client.responses.create({model,input:[{role:'system',content:SYSTEM_PROMPT},{role:'user',content:prompt}],text:{format:{type:'json_schema',...JSON_SCHEMA}}},{signal:controller.signal}); const raw=res.output_text; if(!raw) throw new Error('empty model output'); return raw;}catch(error){if(error instanceof Error && error.name==='AbortError') throw new AnalysisError('OpenAI extraction timed out before returning structured evidence. Please retry; no demo data was returned.',504); throw error}finally{clearTimeout(timer)}}
function validateRawAnalysis(raw:string,model:string,requestId:string){let parsed:unknown; const parseStarted=Date.now(); try{parsed=JSON.parse(raw)}catch{throw new Error('Structured analysis validation failed: model returned invalid JSON')} logTiming(requestId,'structured_output.parsing',parseStarted); return validateAnalysis(parsed,{modelUsed:model,requestId});}
export function prepareExtractionText(text:string,maxChars=MAX_EXTRACTION_TEXT_CHARS){if(text.length<=maxChars)return text; const sections=text.split(/(?=\nDOCUMENT: |\n\[[^\]]+ page \d+\])/g).filter(Boolean); if(!sections.length)return `${text.slice(0,Math.floor(maxChars/2))}\n\n[Middle content compacted for context safety]\n\n${text.slice(-Math.floor(maxChars/2))}`; const budget=Math.max(1200,Math.floor(maxChars/sections.length)); const compacted=sections.map((section)=>section.length<=budget?section:`${section.slice(0,Math.floor(budget*.65))}\n[Section compacted; preserving tail]\n${section.slice(-Math.floor(budget*.35))}`); const joined=compacted.join('\n'); if(joined.length<=maxChars)return joined; const marker='\n[Package compacted; preserving final pages]\n'; const tailBudget=Math.floor(maxChars*.25); const headBudget=maxChars-tailBudget-marker.length; return `${joined.slice(0,headBudget)}${marker}${joined.slice(-tailBudget)}`}
export function chunkSolicitationPackage(text:string,maxChars=MAX_CHUNK_CHARS){const sections=text.split(/(?=\nDOCUMENT: |\n\[[^\]]+ page \d+\])/g).filter(Boolean); const chunks:string[]=[]; let current=''; for(const section of sections.length?sections:[text]){ if(section.length>maxChars){ if(current){chunks.push(current); current=''} for(let i=0;i<section.length;i+=maxChars) chunks.push(section.slice(i,i+maxChars)); continue } if(current.length+section.length>maxChars){chunks.push(current); current=section}else current+=section } if(current) chunks.push(current); return chunks; }
export async function analyzeSolicitationPdfFiles(files:{name:string;buffer:Buffer}[], requestId:string=crypto.randomUUID()): Promise<BidAnalysis>{
 if(!process.env.OPENAI_API_KEY) throw new AnalysisError('OpenAI is not configured. Add OPENAI_API_KEY before analyzing real solicitations.',500);
 const model=process.env.OPENAI_MODEL||'gpt-5.6'; const client=new OpenAI({apiKey:process.env.OPENAI_API_KEY});
 try{const fileInputs=files.map(f=>({type:'input_file' as const,filename:f.name,file_data:`data:application/pdf;base64,${f.buffer.toString('base64')}`})); const raw=await timed(requestId,'openai.direct_pdf_request',async()=>{const res:any=await client.responses.create({model,input:[{role:'system',content:SYSTEM_PROMPT},{role:'user',content:[{type:'input_text',text:'Extract only evidence-backed solicitation facts from these PDF files. Use page citations only if reliably identified; otherwise set pageNumber to null and preserve documentName. Do not decide final scores; deterministic code will calculate them.'},...fileInputs]}],text:{format:{type:'json_schema',...JSON_SCHEMA}}}); if(!res.output_text) throw new AnalysisError('OpenAI returned no analysis content for the uploaded PDF files.',502); return res.output_text}); return timedSync(requestId,'parse.normalize.score.direct_pdf',()=>validateRawAnalysis(raw,model,requestId));}
 catch(error){ if(error instanceof AnalysisError) throw error; if(error instanceof Error && error.message.startsWith('Structured analysis validation failed')) throw new AnalysisError(error.message,502); if(isDirectPdfUnsupportedError(error)) throw new AnalysisError('No selectable PDF text was found, and direct scanned-PDF analysis is not available for the configured model. Upload an OCR/searchable PDF copy.',422); throw new AnalysisError('OpenAI could not analyze the uploaded PDF files at this time. No demo data was returned; please retry later or verify model access.',502)}
}
export function isDirectPdfUnsupportedError(error:unknown){const message=error instanceof Error?error.message.toLowerCase():String(error).toLowerCase(); return ['unsupported file','unsupported input_file','file inputs are not supported','pdf input is not supported','could not read the file','unable to read the pdf','invalid file data'].some(token=>message.includes(token))}
