import type { BidAnalysis } from '@/lib/types';
export const ANALYSIS_VERSION = '2.0.0';
export const JSON_SCHEMA = { name:'bidpilot_analysis_v2', schema:{ type:'object', additionalProperties:true, required:['summary','lineItems','recommendation','recommendationReasoning','checklist'], properties:{ summary:{type:'object'}, lineItems:{type:'array'}, recommendation:{enum:['Bid','No Bid','Needs Clarification']}, recommendationReasoning:{type:'string'}, checklist:{type:'array'} } }, strict:false };
const field=(v:string): any=>({value:v,confidence:'Needs Clarification',status:'Needs Clarification'});
export function normalizeAnalysis(input: any, meta:{modelUsed:string;requestId:string}): BidAnalysis {
 if(!input||typeof input!=='object') throw new Error('The model returned an invalid analysis object.');
 const s=input.summary||{}; const summary:any={...s}; for(const k of ['bidNumber','title','agency','dueDateTime','submissionMethod','deliveryRequirements','licensingRequirements','bondingRequirements']) summary[k]=normalizeField(s[k]);
 const rec=input.recommendation; if(!['Bid','No Bid','Needs Clarification'].includes(rec)) throw new Error('The model returned an invalid recommendation.');
 const lineItems=Array.isArray(input.lineItems)?input.lineItems.map((l:any,i:number)=>({id:String(l.id||`L${i+1}`),name:String(l.name||'Unnamed line item'),description:String(l.description||''),quantity:Number.isFinite(Number(l.quantity))?Number(l.quantity):0,unit:String(l.unit||''),deliveryRequirement:String(l.deliveryRequirement||''),mandatoryRequirements:Array.isArray(l.mandatoryRequirements)?l.mandatoryRequirements.map(String):[],risks:Array.isArray(l.risks)?l.risks.map(String):[],fitScore:Math.max(0,Math.min(10,Number(l.fitScore)||0)),fitReasoning:String(l.fitReasoning||''),recommendation:['Bid','No Bid','Needs Clarification'].includes(l.recommendation)?l.recommendation:'Needs Clarification'})):[];
 return { analysisVersion: input.analysisVersion||ANALYSIS_VERSION, modelUsed: meta.modelUsed, requestId: meta.requestId, generatedAt: new Date().toISOString(), summary, lineItems, mandatoryRequirements:arr(input.mandatoryRequirements), disqualificationRisks:arr(input.disqualificationRisks), recommendation:rec, recommendationReasoning:String(input.recommendationReasoning||''), opportunityScore:score(input.opportunityScore), subScores: typeof input.subScores==='object'&&input.subScores?Object.fromEntries(Object.entries(input.subScores).map(([k,v])=>[k,score(v)])): {}, hardStops:arr(input.hardStops), clarificationGates:arr(input.clarificationGates), positiveDrivers:arr(input.positiveDrivers), keyConcerns:arr(input.keyConcerns), complianceMatrix:Array.isArray(input.complianceMatrix)?input.complianceMatrix.map((c:any,i:number)=>({id:String(c.id||`C${i+1}`),requirement:String(c.requirement||''),category:c.category||'Administrative',mandatory:Boolean(c.mandatory),status:['Compliant','Not Compliant','Unknown','Needs Clarification'].includes(c.status)?c.status:'Unknown',riskLevel:['Low','Medium','High'].includes(c.riskLevel)?c.riskLevel:'Medium',evidence:c.evidence?String(c.evidence):undefined,pageNumber:Number.isFinite(Number(c.pageNumber))?Number(c.pageNumber):undefined,documentName:c.documentName?String(c.documentName):undefined,actionNeeded:String(c.actionNeeded||'Verify requirement'),owner:String(c.owner||'Bid Lead')})):[], clarificationQuestions:Array.isArray(input.clarificationQuestions)?input.clarificationQuestions.map((q:any)=>({question:String(q.question||''),whyItMatters:String(q.whyItMatters||''),relatedRequirement:String(q.relatedRequirement||''),priority:['Low','Medium','High'].includes(q.priority)?q.priority:'Medium'})).filter((q:any)=>q.question):[], checklist:Array.isArray(input.checklist)?input.checklist.map((c:any,i:number)=>({id:String(c.id||`T${i+1}`),task:String(c.task||''),owner:String(c.owner||'Bid Lead'),due:String(c.due||'Needs Clarification'),status:['Not Started','In Progress','Complete','Blocked'].includes(c.status)?c.status:'Not Started',riskLevel:['Low','Medium','High'].includes(c.riskLevel)?c.riskLevel:'Medium',priority:c.priority||c.riskLevel||'Medium',blocking:Boolean(c.blocking),sourceRequirement:c.sourceRequirement?String(c.sourceRequirement):undefined})).filter((c:any)=>c.task):[], sourceNotes:arr(input.sourceNotes) };
}
function normalizeField(f:any){ if(!f||typeof f!=='object')return field('Not Found'); return {value:String(f.value??'Not Found'),confidence:['High','Medium','Low','Needs Clarification'].includes(f.confidence)?f.confidence:'Needs Clarification',evidence:f.evidence?String(f.evidence).slice(0,300):undefined,pageNumber:Number.isFinite(Number(f.pageNumber))?Number(f.pageNumber):undefined,documentName:f.documentName?String(f.documentName):undefined,status:['Fact','Inference','Not Found','Needs Clarification'].includes(f.status)?f.status:'Needs Clarification'}; }
function arr(v:any){return Array.isArray(v)?v.map(String):[]}
function score(v:any){return {score:Math.max(0,Math.min(100,Number(v?.score)||0)),confidence:['High','Medium','Low','Needs Clarification'].includes(v?.confidence)?v.confidence:'Needs Clarification',reasoning:String(v?.reasoning||'')}}
