import type { BidAnalysis, ClarificationAudience, ComplianceItem } from '../types';
export type CanonicalCategory='Submission'|'Administrative'|'Technical'|'Commercial'|'Registration'|'Insurance'|'Bonding'|'Delivery'|'Legal'|'Certification'|'Other';
export type BidderStatus='Confirmed Compliant'|'Unknown'|'Needs Clarification'|'Confirmed Noncompliant'|'Not Applicable';
export type CanonicalRequirement={id:string;canonicalKey:string;category:CanonicalCategory;requirementType:string;title:string;normalizedText:string;mandatory:boolean;sourceEvidence:string[];documentNames:string[];pageNumbers:number[];solicitationStatus:'Required'|'Optional'|'Disqualification Rule'|'Ambiguous';bidderStatus:BidderStatus;riskLevel:'Low'|'Medium'|'High';clarificationAudience:ClarificationAudience;actionOwner:string};
type KnownRow={re:RegExp;key:string;category:CanonicalCategory;type:string;title:string;audience:ClarificationAudience;owner:string};
const KNOWN:KnownRow[]=[
 {re:/late (receipt|bid|bids)|received by|bid must be received|proposal must be received|deadline|due date|bid due|proposal due/i,key:'SUBMISSION_DEADLINE',category:'Submission',type:'Deadline',title:'Submission Deadline',audience:'Internal Bid Team',owner:'Bid Lead'},
 {re:/hard cop(y|ies).*not accepted|electronic submission|required.*electronic|submit by email|lsubids|submission method|portal|physical delivery/i,key:'SUBMISSION_METHOD',category:'Submission',type:'Submission',title:'Submission Method',audience:'Internal Bid Team',owner:'Bid Lead'},
 {re:/quote net pricing.*fob|net pricing.*fob|fob .*destination|destination inclusive of shipping/i,key:'FOB_DESTINATION_PRICING',category:'Commercial',type:'FOB Pricing',title:'FOB Destination Pricing',audience:'Internal Bid Team',owner:'Finance'},
 {re:/shipping and handling included|shipping.*included|freight.*included|inclusive of shipping|freight/i,key:'FREIGHT_INCLUDED',category:'Commercial',type:'Freight',title:'Freight and Shipping Included',audience:'Internal Bid Team',owner:'Finance'},
 {re:/workday|supplier (registration|enrollment)|enroll.*supplier/i,key:'SUPPLIER_REGISTRATION',category:'Registration',type:'Registration',title:'Supplier Registration',audience:'Internal Bid Team',owner:'Internal Bid Team'},
 {re:/(w-?9|w-?8|tax documentation|tax form)/i,key:'TAX_DOCUMENTATION',category:'Administrative',type:'Tax Documentation',title:'Tax Documentation',audience:'Internal Bid Team',owner:'Internal Bid Team'},
 {re:/insurance/i,key:'INSURANCE_REQUIREMENTS',category:'Insurance',type:'Insurance',title:'Insurance Requirements',audience:'Internal Bid Team',owner:'Legal/Compliance'},
 {re:/bond|bonding/i,key:'BONDING_REQUIREMENTS',category:'Bonding',type:'Bonding',title:'Bonding Requirements',audience:'Internal Bid Team',owner:'Legal/Compliance'},
 {re:/signature|signed/i,key:'AUTHORIZED_SIGNATURE',category:'Administrative',type:'Signature',title:'Authorized Signature',audience:'Internal Bid Team',owner:'Bid Lead'},
 {re:/required form|bid form|forms/i,key:'REQUIRED_FORMS',category:'Administrative',type:'Forms',title:'Required Forms',audience:'Internal Bid Team',owner:'Bid Lead'},
 {re:/email subject|subject line/i,key:'EMAIL_SUBJECT',category:'Submission',type:'Email',title:'Required Email Subject',audience:'Internal Bid Team',owner:'Bid Lead'},
 {re:/attachment|file size/i,key:'ATTACHMENT_SIZE_LIMIT',category:'Submission',type:'Attachment',title:'Attachment Size Limit',audience:'Internal Bid Team',owner:'Bid Lead'},
 {re:/addenda|addendum/i,key:'ADDENDA_ACKNOWLEDGEMENT',category:'Administrative',type:'Addenda',title:'Addenda Acknowledgement',audience:'Internal Bid Team',owner:'Bid Lead'},
 {re:/delivery|lead time/i,key:'DELIVERY_LEAD_TIME',category:'Delivery',type:'Delivery',title:'Delivery Lead Time',audience:'Supplier / Manufacturer',owner:'Operations'},
 {re:/manufacturer|brand|model/i,key:'MANUFACTURER_MODEL_REQUIRED',category:'Technical',type:'Product',title:'Manufacturer / Model Required',audience:'Supplier / Manufacturer',owner:'Technical'},
 {re:/technical|specification|piv/i,key:'TECHNICAL_COMPLIANCE',category:'Technical',type:'Technical',title:'Technical Compliance',audience:'Supplier / Manufacturer',owner:'Technical'},
 {re:/installation/i,key:'INSTALLATION_REQUIRED',category:'Technical',type:'Installation',title:'Installation Required',audience:'Supplier / Manufacturer',owner:'Operations'},
 {re:/training/i,key:'TRAINING_REQUIRED',category:'Technical',type:'Training',title:'Training Required',audience:'Supplier / Manufacturer',owner:'Operations'},
 {re:/warranty/i,key:'WARRANTY_REQUIRED',category:'Commercial',type:'Warranty',title:'Warranty Required',audience:'Supplier / Manufacturer',owner:'Sourcing'},
];
const TITLE_BY_KEY=Object.fromEntries(KNOWN.map(k=>[k.key,k.title]));
export function normalizeRequirementText(text:string){return dedupeTokens(text.toLowerCase().replace(/w\s*-\s*/g,'w-').replace(/[^a-z0-9]+/g,' ').replace(/\b(must|shall|required|requires|requirement|supplier|bidder|vendor|contractor|lsu)\b/g,' ').replace(/\s+/g,' ').trim()).join(' ')}
export function canonicalKeyFor(text:string,category?:string){const cat=String(category||''); if(/^Insurance$/i.test(cat))return 'INSURANCE_REQUIREMENTS'; if(/^Bonding$/i.test(cat))return 'BONDING_REQUIREMENTS'; for(const row of KNOWN) if(row.re.test(text)) return row.key; const categoryToken=cleanCategory(category); const tokens=dedupeTokens(normalizeRequirementText(text).split(' ').filter(t=>t&&t!==categoryToken.toLowerCase())).slice(0,9); const slug=tokens.join('_').toUpperCase()||'REQUIREMENT'; return `${categoryToken}_${slug}`.replace(/^(OTHER_)+OTHER_/,'OTHER_').replace(/_+/g,'_')}
function cleanCategory(category?:string){const c=String(category||'Other').replace(/[^a-zA-Z]/g,'').toUpperCase(); return c&&c!=='OTHEROTHER'?c:'OTHER'}
function dedupeTokens(input:string|string[]){const raw=Array.isArray(input)?input:input.split(' '); const out:string[]=[]; for(const token of raw){if(token&&token!==out[out.length-1]) out.push(token)} return out}
export function canonicalizeRequirements(analysis:BidAnalysis):CanonicalRequirement[]{const seed:CanonicalRequirement[]=[]; for(const item of analysis.complianceMatrix) seed.push(fromCompliance(item)); for(const rule of analysis.disqualificationRisks) seed.push(fromText(rule,'Disqualification Rule',true)); for(const req of analysis.mandatoryRequirements) seed.push(fromText(req,'Required',true)); return dedupeRequirements(seed)}
function fromCompliance(item:ComplianceItem):CanonicalRequirement{const key=canonicalKeyFor(`${item.category} ${item.requirement}`,item.category); const meta=metaForKey(key,item.requirement,item.category); return {id:key,canonicalKey:key,category:meta.category,requirementType:meta.type,title:meta.title,normalizedText:normalizeRequirementText(item.requirement),mandatory:item.mandatory,sourceEvidence:item.evidence?[item.evidence]:[],documentNames:item.documentName?[item.documentName]:[],pageNumbers:item.pageNumber?[item.pageNumber]:[],solicitationStatus:item.mandatory?'Required':'Optional',bidderStatus:bidderStatusFromCompliance(item.status),riskLevel:item.riskLevel,clarificationAudience:meta.audience,actionOwner:routeOwner(meta.owner,item),};}
function fromText(text:string,status:CanonicalRequirement['solicitationStatus'],mandatory:boolean):CanonicalRequirement{const key=canonicalKeyFor(text); const meta=metaForKey(key,text); return {id:key,canonicalKey:key,category:meta.category,requirementType:meta.type,title:meta.title,normalizedText:normalizeRequirementText(text),mandatory,sourceEvidence:[text],documentNames:[],pageNumbers:[],solicitationStatus:status,bidderStatus:'Unknown',riskLevel:status==='Disqualification Rule'?'High':'Medium',clarificationAudience:meta.audience,actionOwner:meta.owner};}
function metaForKey(key:string,text:string,category?:string){const row=KNOWN.find(k=>k.key===key)||KNOWN.find(k=>k.re.test(text)); return row?{category:row.category,type:row.type,title:row.title,audience:row.audience,owner:row.owner}:{category:(category as CanonicalCategory)||'Other',type:'Requirement',title:titleize(key),audience:'Internal Bid Team' as ClarificationAudience,owner:'Bid Lead'}}
function titleize(key:string){if(TITLE_BY_KEY[key])return TITLE_BY_KEY[key]; const tokens=dedupeTokens(key.replace(/^(OTHER_|COMMERCIAL_|SUBMISSION_|ADMINISTRATIVE_|TECHNICAL_)/,'').toLowerCase().split('_')); return tokens.map(w=>w[0]?.toUpperCase()+w.slice(1)).join(' ')}
function bidderStatusFromCompliance(status:string):BidderStatus{if(status==='Compliant')return 'Confirmed Compliant'; if(status==='Not Compliant')return 'Confirmed Noncompliant'; if(status==='Needs Clarification')return 'Needs Clarification'; return 'Unknown'}
function routeOwner(owner:string,item:ComplianceItem){if(/buyer|contracting officer|co\b/i.test(item.owner))return owner; return item.owner||owner}
function riskRank(r:string){return r==='High'?3:r==='Medium'?2:1}
function statusRank(s:BidderStatus){return s==='Confirmed Noncompliant'?4:s==='Needs Clarification'?3:s==='Unknown'?2:s==='Confirmed Compliant'?1:0}
export function dedupeRequirements(items:CanonicalRequirement[]){const map=new Map<string,CanonicalRequirement>(); for(const item of items){const existing=map.get(item.canonicalKey); if(!existing){map.set(item.canonicalKey,{...item,id:item.canonicalKey}); continue} existing.mandatory=existing.mandatory||item.mandatory; existing.sourceEvidence=[...new Set([...existing.sourceEvidence,...item.sourceEvidence])]; existing.documentNames=[...new Set([...existing.documentNames,...item.documentNames])]; existing.pageNumbers=[...new Set([...existing.pageNumbers,...item.pageNumbers])].sort((a,b)=>a-b); if(riskRank(item.riskLevel)>riskRank(existing.riskLevel)) existing.riskLevel=item.riskLevel; if(statusRank(item.bidderStatus)>statusRank(existing.bidderStatus)) existing.bidderStatus=item.bidderStatus; if(existing.solicitationStatus!=='Required'&&item.solicitationStatus==='Required') existing.solicitationStatus='Required'; } return [...map.values()].sort((a,b)=>a.canonicalKey.localeCompare(b.canonicalKey))}
export function unresolvedRequirements(requirements:CanonicalRequirement[]){return requirements.filter(r=>r.mandatory&&(r.bidderStatus==='Unknown'||r.bidderStatus==='Needs Clarification'))}
export function activeHardStopsFromRequirements(requirements:CanonicalRequirement[]){return requirements.filter(r=>r.mandatory&&r.bidderStatus==='Confirmed Noncompliant').map(r=>`Confirmed mandatory noncompliance: ${r.title}`)}
export function complianceItemsFromCanonical(requirements:CanonicalRequirement[]):ComplianceItem[]{return requirements.filter(r=>r.solicitationStatus!=='Disqualification Rule').map(r=>({id:r.id,requirement:r.title,category:r.category==='Certification'?'Administrative':r.category,mandatory:r.mandatory,status:r.bidderStatus==='Confirmed Compliant'?'Compliant':r.bidderStatus==='Confirmed Noncompliant'?'Not Compliant':r.bidderStatus==='Needs Clarification'?'Needs Clarification':'Unknown',riskLevel:r.riskLevel,evidence:r.sourceEvidence[0]||'',documentName:r.documentNames[0],pageNumber:r.pageNumbers[0],actionNeeded:r.bidderStatus==='Confirmed Compliant'?'Prepare evidence for submission':`Resolve ${r.title}`,owner:r.actionOwner} as ComplianceItem))}
