import type { BidAnalysis, ClarificationAudience, ComplianceItem } from '../types';
export type CanonicalCategory='Submission'|'Administrative'|'Technical'|'Commercial'|'Registration'|'Insurance'|'Bonding'|'Delivery'|'Legal'|'Certification'|'Other';
export type BidderStatus='Confirmed Compliant'|'Unknown'|'Needs Clarification'|'Confirmed Noncompliant'|'Not Applicable';
export type CanonicalRequirement={id:string;canonicalKey:string;category:CanonicalCategory;requirementType:string;title:string;normalizedText:string;mandatory:boolean;sourceEvidence:string[];documentNames:string[];pageNumbers:number[];solicitationStatus:'Required'|'Optional'|'Disqualification Rule'|'Ambiguous';bidderStatus:BidderStatus;riskLevel:'Low'|'Medium'|'High';clarificationAudience:ClarificationAudience;actionOwner:string};
export type CanonicalCatalogItem={id:string;title:string;category:CanonicalCategory;requirementType:string;defaultMandatoryBehavior:'Required'|'Optional'|'Contextual';defaultRiskLevel:'Low'|'Medium'|'High';defaultActionOwner:string;defaultClarificationAudience:ClarificationAudience;aliases:RegExp};
export const CANONICAL_REQUIREMENT_CATALOG:CanonicalCatalogItem[]=[
 {id:'SUBMISSION_DEADLINE',title:'Submission Deadline',category:'Submission',requirementType:'Deadline',defaultMandatoryBehavior:'Contextual',defaultRiskLevel:'Medium',defaultActionOwner:'Internal Bid Team',defaultClarificationAudience:'Internal Bid Team',aliases:/late (receipt|bid|bids)|received by|receipt after deadline|bid must be received|proposal must be received|deadline|due date|bid due|proposal due/i},
 {id:'SUBMISSION_COPY_REQUIREMENTS',title:'Original and Redacted Copy Requirements',category:'Submission',requirementType:'Copies',defaultMandatoryBehavior:'Contextual',defaultRiskLevel:'Medium',defaultActionOwner:'Internal Bid Team',defaultClarificationAudience:'Internal Bid Team',aliases:/original.*redacted|redacted.*copy|submit original.*copy|redacted electronic/i},
 {id:'SUBMISSION_METHOD',title:'Submission Method',category:'Submission',requirementType:'Submission',defaultMandatoryBehavior:'Contextual',defaultRiskLevel:'Medium',defaultActionOwner:'Internal Bid Team',defaultClarificationAudience:'Internal Bid Team',aliases:/hard[- ]?cop(y|ies).*not (be )?(accepted|evaluated)|hard[- ]?copy bids.*not (be )?evaluated|hard[- ]?copy submission|only electronic|electronic submission|required.*electronic|submit electronically|submit by email|email submission|required email|return bid to|do not submit directly|directly to the buyer|email bids|lsubids|submission method|portal|physical delivery/i},
 {id:'ATTACHMENT_SIZE_LIMIT',title:'Attachment Size Limit',category:'Submission',requirementType:'Attachment',defaultMandatoryBehavior:'Contextual',defaultRiskLevel:'Medium',defaultActionOwner:'Internal Bid Team',defaultClarificationAudience:'Internal Bid Team',aliases:/attachment|file size|\b\d+\s*mb\b|megabyte/i},
 {id:'EMAIL_SUBJECT',title:'Required Email Subject',category:'Submission',requirementType:'Email',defaultMandatoryBehavior:'Contextual',defaultRiskLevel:'Medium',defaultActionOwner:'Internal Bid Team',defaultClarificationAudience:'Internal Bid Team',aliases:/email subject|subject line/i},
 {id:'AUTHORIZED_SIGNATURE',title:'Authorized Signature',category:'Administrative',requirementType:'Signature',defaultMandatoryBehavior:'Contextual',defaultRiskLevel:'Medium',defaultActionOwner:'Internal Bid Team',defaultClarificationAudience:'Internal Bid Team',aliases:/signature|signed|authorized representative/i},
 {id:'REQUIRED_FORMS',title:'Required Solicitation Forms',category:'Administrative',requirementType:'Forms',defaultMandatoryBehavior:'Contextual',defaultRiskLevel:'Medium',defaultActionOwner:'Internal Bid Team',defaultClarificationAudience:'Internal Bid Team',aliases:/required form|bid form|forms/i},
 {id:'ADDENDA_ACKNOWLEDGEMENT',title:'Addenda Acknowledgement',category:'Administrative',requirementType:'Addenda',defaultMandatoryBehavior:'Contextual',defaultRiskLevel:'Medium',defaultActionOwner:'Internal Bid Team',defaultClarificationAudience:'Internal Bid Team',aliases:/addenda|addendum/i},
 {id:'SUPPLIER_REGISTRATION',title:'Supplier Registration',category:'Registration',requirementType:'Registration',defaultMandatoryBehavior:'Contextual',defaultRiskLevel:'Medium',defaultActionOwner:'Internal Bid Team',defaultClarificationAudience:'Internal Bid Team',aliases:/workday|supplier (registration|enrollment)|enroll.*supplier/i},
 {id:'TAX_DOCUMENTATION',title:'Tax Documentation',category:'Registration',requirementType:'Tax Documentation',defaultMandatoryBehavior:'Contextual',defaultRiskLevel:'Medium',defaultActionOwner:'Internal Bid Team',defaultClarificationAudience:'Internal Bid Team',aliases:/(w-?9|w-?8|tax documentation|tax form)/i},
 {id:'INSURANCE_REQUIREMENTS',title:'Insurance Requirements',category:'Insurance',requirementType:'Insurance',defaultMandatoryBehavior:'Contextual',defaultRiskLevel:'Medium',defaultActionOwner:'Internal Bid Team',defaultClarificationAudience:'Internal Bid Team',aliases:/insurance/i},
 {id:'DEBARMENT_CERTIFICATION',title:'Suspension and Debarment Certification',category:'Certification',requirementType:'Certification',defaultMandatoryBehavior:'Contextual',defaultRiskLevel:'Medium',defaultActionOwner:'Internal Bid Team',defaultClarificationAudience:'Internal Bid Team',aliases:/(no suspension or debarment|not suspended or debarred|not debarred|not suspended|suspended|suspension|debarred|debarment|excluded|exclusion).*(subcontractors?|principals?|supplier|vendor|contractor|certif)?|certif.*(not|no).*(suspended|debarred|debarment|suspension|excluded)|subcontractors?.*(principals?)?.*(suspended|debarred|excluded)|principals?.*(suspended|debarred|excluded)/i},
 {id:'BONDING_REQUIREMENTS',title:'Bonding Requirements',category:'Bonding',requirementType:'Bonding',defaultMandatoryBehavior:'Contextual',defaultRiskLevel:'Medium',defaultActionOwner:'Internal Bid Team',defaultClarificationAudience:'Internal Bid Team',aliases:/bond|bonding/i},
 {id:'FOB_DESTINATION_PRICING',title:'FOB Destination Pricing',category:'Commercial',requirementType:'FOB Pricing',defaultMandatoryBehavior:'Contextual',defaultRiskLevel:'Medium',defaultActionOwner:'Internal Bid Team',defaultClarificationAudience:'Internal Bid Team',aliases:/quote net pricing.*fob|net pricing.*fob|fob .*destination|fob lsu destination|destination inclusive of shipping/i},
 {id:'FREIGHT_INCLUDED',title:'Freight and Shipping Included',category:'Commercial',requirementType:'Freight',defaultMandatoryBehavior:'Contextual',defaultRiskLevel:'Medium',defaultActionOwner:'Internal Bid Team',defaultClarificationAudience:'Internal Bid Team',aliases:/shipping and handling included|shipping.*included|freight.*included|inclusive of shipping|freight/i},
 {id:'PRICE_VALIDITY_PERIOD',title:'Price Validity Period',category:'Commercial',requirementType:'Price Validity',defaultMandatoryBehavior:'Contextual',defaultRiskLevel:'Medium',defaultActionOwner:'Internal Bid Team',defaultClarificationAudience:'Internal Bid Team',aliases:/prices? (remain|shall remain|must remain)? ?(firm|valid)|maintain prices? for acceptance|offer (must )?(remain|remains) (open|valid) for acceptance|bid validity period|price acceptance period|price validity period|pricing (shall remain )?valid|prices valid|hold pricing/i},
 {id:'AWARD_BASIS',title:'Award Basis',category:'Commercial',requirementType:'Award',defaultMandatoryBehavior:'Contextual',defaultRiskLevel:'Medium',defaultActionOwner:'Internal Bid Team',defaultClarificationAudience:'Internal Bid Team',aliases:/award basis|all[- ]or[- ]none|separate.*grouped.*all[- ]or[- ]none|award.*conflict|evaluation basis/i},
 {id:'DELIVERY_LEAD_TIME',title:'Delivery Lead Time',category:'Delivery',requirementType:'Delivery',defaultMandatoryBehavior:'Contextual',defaultRiskLevel:'Medium',defaultActionOwner:'Supplier / Manufacturer',defaultClarificationAudience:'Supplier / Manufacturer',aliases:/delivery|lead time/i},
 {id:'MANUFACTURER_MODEL_REQUIRED',title:'Manufacturer / Model Required',category:'Technical',requirementType:'Product',defaultMandatoryBehavior:'Contextual',defaultRiskLevel:'Medium',defaultActionOwner:'Supplier / Manufacturer',defaultClarificationAudience:'Supplier / Manufacturer',aliases:/manufacturer|brand|model( number)?/i},
 {id:'LASER_SAFETY_COMPLIANCE',title:'Laser Safety Compliance',category:'Technical',requirementType:'Safety',defaultMandatoryBehavior:'Contextual',defaultRiskLevel:'High',defaultActionOwner:'Supplier / Manufacturer',defaultClarificationAudience:'Supplier / Manufacturer',aliases:/ansi\s*z136\.1|iec\s*60825-?1|laser safety/i},
 {id:'INSTALLATION_REQUIRED',title:'Installation Required',category:'Technical',requirementType:'Installation',defaultMandatoryBehavior:'Contextual',defaultRiskLevel:'Medium',defaultActionOwner:'Supplier / Manufacturer',defaultClarificationAudience:'Supplier / Manufacturer',aliases:/onsite installation|on-site installation|installation/i},
 {id:'TRAINING_REQUIRED',title:'Training Required',category:'Technical',requirementType:'Training',defaultMandatoryBehavior:'Contextual',defaultRiskLevel:'Medium',defaultActionOwner:'Supplier / Manufacturer',defaultClarificationAudience:'Supplier / Manufacturer',aliases:/onsite training|on-site training|training/i},
 {id:'WARRANTY_REQUIRED',title:'Warranty Required',category:'Commercial',requirementType:'Warranty',defaultMandatoryBehavior:'Contextual',defaultRiskLevel:'Medium',defaultActionOwner:'Supplier / Manufacturer',defaultClarificationAudience:'Supplier / Manufacturer',aliases:/one[- ]year warranty|warranty/i},
 {id:'TECHNICAL_DOCUMENTATION',title:'Technical Documentation',category:'Technical',requirementType:'Documentation',defaultMandatoryBehavior:'Contextual',defaultRiskLevel:'Medium',defaultActionOwner:'Supplier / Manufacturer',defaultClarificationAudience:'Supplier / Manufacturer',aliases:/product spec sheets?|technical documentation|data sheet/i},
 {id:'TECHNICAL_COMPLIANCE',title:'Technical Compliance',category:'Technical',requirementType:'Technical',defaultMandatoryBehavior:'Contextual',defaultRiskLevel:'Medium',defaultActionOwner:'Supplier / Manufacturer',defaultClarificationAudience:'Supplier / Manufacturer',aliases:/technical|specification|piv|625\s*(hz|frames per second|fps)|15[- ]?minute|field of view|vector spacing|\bsnr\b|data latency|latency|2\s*mm/i},
];
const TITLE_BY_KEY=Object.fromEntries(CANONICAL_REQUIREMENT_CATALOG.map(k=>[k.id,k.title]));
export function normalizeRequirementText(text:string){return dedupeTokens(text.toLowerCase().replace(/w\s*-\s*/g,'w-').replace(/[^a-z0-9]+/g,' ').replace(/\b(must|shall|required|requires|requirement|supplier|bidder|vendor|contractor|lsu|applicable|evaluated|accepted)\b/g,' ').replace(/\s+/g,' ').trim()).join(' ')}
export function canonicalKeyFor(text:string,category?:string){const cat=String(category||''); if(/^Insurance$/i.test(cat))return 'INSURANCE_REQUIREMENTS'; if(/^Bonding$/i.test(cat))return 'BONDING_REQUIREMENTS'; if(/signature|signed|authorized representative/i.test(text)) return 'AUTHORIZED_SIGNATURE'; for(const item of CANONICAL_REQUIREMENT_CATALOG) if(item.aliases.test(text)) return item.id; if(/^Technical$/i.test(cat)) return 'TECHNICAL_COMPLIANCE'; const categoryToken=cleanCategory(category); const tokens=dedupeTokens(normalizeRequirementText(text).split(' ').filter(t=>t&&t!==categoryToken.toLowerCase())).slice(0,5); const slug=tokens.join('_').toUpperCase()||'REQUIREMENT'; return `${categoryToken}_${slug}`.replace(/^(OTHER_)+OTHER_/,'OTHER_').replace(/_+/g,'_')}
function cleanCategory(category?:string){const c=String(category||'Other').replace(/[^a-zA-Z]/g,'').toUpperCase(); return c&&c!=='OTHEROTHER'?c:'OTHER'}
function dedupeTokens(input:string|string[]){const raw=Array.isArray(input)?input:input.split(' '); const out:string[]=[]; for(const token of raw){if(token&&token!==out[out.length-1]) out.push(token)} return out}
export function canonicalizeRequirements(analysis:BidAnalysis):CanonicalRequirement[]{const seed:CanonicalRequirement[]=[]; for(const item of analysis.complianceMatrix) seed.push(fromCompliance(item)); for(const rule of analysis.disqualificationRisks) seed.push(fromText(rule,'Disqualification Rule',true)); for(const req of analysis.mandatoryRequirements) seed.push(fromText(req,'Required',true)); return dedupeRequirements(seed)}
function fromCompliance(item:ComplianceItem):CanonicalRequirement{const key=canonicalKeyFor(`${item.category} ${item.requirement}`,item.category); const meta=metaForKey(key,item.requirement,item.category); return {id:key,canonicalKey:key,category:meta.category,requirementType:meta.type,title:meta.title,normalizedText:normalizeRequirementText(item.requirement),mandatory:item.mandatory,sourceEvidence:item.evidence?[item.evidence]:[],documentNames:item.documentName?[item.documentName]:[],pageNumbers:item.pageNumber?[item.pageNumber]:[],solicitationStatus:item.mandatory?'Required':'Optional',bidderStatus:bidderStatusFromCompliance(item.status),riskLevel:item.riskLevel,clarificationAudience:meta.audience,actionOwner:routeOwner(meta.owner,item),};}
function fromText(text:string,status:CanonicalRequirement['solicitationStatus'],mandatory:boolean):CanonicalRequirement{const key=canonicalKeyFor(text); const meta=metaForKey(key,text); return {id:key,canonicalKey:key,category:meta.category,requirementType:meta.type,title:meta.title,normalizedText:normalizeRequirementText(text),mandatory,sourceEvidence:[text],documentNames:[],pageNumbers:[],solicitationStatus:status,bidderStatus:'Unknown',riskLevel:status==='Disqualification Rule'?'High':'Medium',clarificationAudience:meta.audience,actionOwner:meta.owner};}
function metaForKey(key:string,text:string,category?:string){const item=CANONICAL_REQUIREMENT_CATALOG.find(k=>k.id===key)||CANONICAL_REQUIREMENT_CATALOG.find(k=>k.aliases.test(text)); return item?{category:item.category,type:item.requirementType,title:item.title,audience:item.defaultClarificationAudience,owner:item.defaultActionOwner}:{category:(category as CanonicalCategory)||'Other',type:'Requirement',title:titleize(key),audience:'Internal Bid Team' as ClarificationAudience,owner:'Internal Bid Team'}}
function titleize(key:string){if(TITLE_BY_KEY[key])return TITLE_BY_KEY[key]; const tokens=dedupeTokens(key.replace(/^(OTHER_|COMMERCIAL_|SUBMISSION_|ADMINISTRATIVE_|TECHNICAL_)/,'').toLowerCase().split('_')); return tokens.map(w=>w[0]?.toUpperCase()+w.slice(1)).join(' ')}
function bidderStatusFromCompliance(status:string):BidderStatus{if(status==='Compliant')return 'Confirmed Compliant'; if(status==='Not Compliant')return 'Confirmed Noncompliant'; if(status==='Needs Clarification')return 'Needs Clarification'; return 'Unknown'}
function routeOwner(owner:string,_item:ComplianceItem){return owner}
function riskRank(r:string){return r==='High'?3:r==='Medium'?2:1}
function statusRank(s:BidderStatus){return s==='Confirmed Noncompliant'?4:s==='Needs Clarification'?3:s==='Unknown'?2:s==='Confirmed Compliant'?1:0}
export function dedupeRequirements(items:CanonicalRequirement[]){const map=new Map<string,CanonicalRequirement>(); for(const item of items){const existing=map.get(item.canonicalKey); if(!existing){map.set(item.canonicalKey,{...item,id:item.canonicalKey}); continue} existing.mandatory=existing.mandatory||item.mandatory; existing.sourceEvidence=[...new Set([...existing.sourceEvidence,...item.sourceEvidence])]; existing.documentNames=[...new Set([...existing.documentNames,...item.documentNames])]; existing.pageNumbers=[...new Set([...existing.pageNumbers,...item.pageNumbers])].sort((a,b)=>a-b); if(riskRank(item.riskLevel)>riskRank(existing.riskLevel)) existing.riskLevel=item.riskLevel; if(statusRank(item.bidderStatus)>statusRank(existing.bidderStatus)) existing.bidderStatus=item.bidderStatus; if(existing.solicitationStatus!=='Required'&&item.solicitationStatus==='Required') existing.solicitationStatus='Required'; } return [...map.values()].sort((a,b)=>a.canonicalKey.localeCompare(b.canonicalKey))}
export function unresolvedRequirements(requirements:CanonicalRequirement[]){return requirements.filter(r=>r.mandatory&&(r.bidderStatus==='Unknown'||r.bidderStatus==='Needs Clarification'))}
export function activeHardStopsFromRequirements(requirements:CanonicalRequirement[]){return requirements.filter(r=>r.mandatory&&r.bidderStatus==='Confirmed Noncompliant').map(r=>`Confirmed mandatory noncompliance: ${r.title}`)}
export function complianceItemsFromCanonical(requirements:CanonicalRequirement[]):ComplianceItem[]{return requirements.filter(r=>r.solicitationStatus!=='Disqualification Rule').map(r=>({id:r.id,requirement:r.title,category:r.category==='Certification'?'Administrative':r.category,mandatory:r.mandatory,status:r.bidderStatus==='Confirmed Compliant'?'Compliant':r.bidderStatus==='Confirmed Noncompliant'?'Not Compliant':r.bidderStatus==='Needs Clarification'?'Needs Clarification':'Unknown',riskLevel:r.riskLevel,evidence:r.sourceEvidence[0]||'',documentName:r.documentNames[0],pageNumber:r.pageNumbers[0],actionNeeded:r.bidderStatus==='Confirmed Compliant'?'Prepare evidence for submission':`Resolve ${r.title}`,owner:r.actionOwner} as ComplianceItem))}

export function mergeDeterministicSignals<T extends {complianceMatrix?:ComplianceItem[];sourceNotes?:string[];summary?:Record<string,any>;mandatoryRequirements?:string[];disqualificationRisks?:string[]}>(analysis:T,documentText=''):T{const clone:any=structuredClone(analysis); clone.complianceMatrix=Array.isArray(clone.complianceMatrix)?clone.complianceMatrix:[]; const corpus=[documentText,...(Array.isArray(clone.sourceNotes)?clone.sourceNotes:[]),...Object.values(clone.summary||{}).flatMap((f:any)=>[f?.value,f?.evidence]),...clone.complianceMatrix.flatMap((c:ComplianceItem)=>[c.requirement,c.evidence]),...(clone.mandatoryRequirements||[]),...(clone.disqualificationRisks||[])].filter(Boolean).join('\n'); const add=(id:string,requirement:string,category:ComplianceItem['category'],riskLevel:ComplianceItem['riskLevel'],owner:string,regex:RegExp)=>{if(!regex.test(corpus))return; if(clone.complianceMatrix.some((c:ComplianceItem)=>canonicalKeyFor(`${c.category} ${c.requirement}`,c.category)===id))return; const evidence=excerptFor(corpus,regex)||requirement; clone.complianceMatrix.push({id,requirement,category,mandatory:true,status:'Unknown',riskLevel,evidence,actionNeeded:`Resolve ${requirement}`,owner});}; add('PRICE_VALIDITY_PERIOD','Price Validity Period','Commercial','Medium','Internal Bid Team',/(prices? (remain|shall remain|must remain) (firm|valid)|maintain prices? for acceptance|offer (must )?(remain|remains) (open|valid) for acceptance|bid prices? valid|bid validity period|price acceptance period|minimum (30|thirty)[ -]?day acceptance period|prices? .*valid .*?(30|thirty) days?)/i); add('DEBARMENT_CERTIFICATION','Suspension and Debarment Certification','Administrative','Medium','Internal Bid Team',/(no suspension or debarment|certif(?:y|ication).*no suspension or debarment|not suspended or debarred|not debarred|supplier.*not.*(suspended|debarred)|subcontractors?.*not.*(suspended|debarred)|principals?.*not.*(suspended|debarred)|excluded parties?.*debarment)/i); add('DELIVERY_LEAD_TIME','Delivery Lead Time','Delivery','Medium','Supplier / Manufacturer',/(delivery (days|time) after receipt of order|state delivery (days|time)|delivery lead[- ]?time|supplier.*delivery.*days|delivery.*aro|after receipt of order)/i); return clone;}
function excerptFor(text:string,regex:RegExp){const match=regex.exec(text); if(!match)return ''; const start=Math.max(0,match.index-120); const end=Math.min(text.length,match.index+match[0].length+160); return text.slice(start,end).replace(/\s+/g,' ').trim();}
