import type { BidAnalysis, ClarificationAudience, ComplianceItem } from '../types';
export type CanonicalCategory='Submission'|'Administrative'|'Technical'|'Commercial'|'Registration'|'Insurance'|'Bonding'|'Delivery'|'Legal'|'Certification'|'Other';
export type BidderStatus='Confirmed Compliant'|'Unknown'|'Needs Clarification'|'Confirmed Noncompliant'|'Not Applicable';
export type CanonicalRequirement={id:string;canonicalKey:string;category:CanonicalCategory;requirementType:string;title:string;normalizedText:string;mandatory:boolean;sourceEvidence:string[];documentNames:string[];pageNumbers:number[];solicitationStatus:'Required'|'Optional'|'Disqualification Rule'|'Ambiguous';bidderStatus:BidderStatus;riskLevel:'Low'|'Medium'|'High';clarificationAudience:ClarificationAudience;actionOwner:string};
const KNOWN:[RegExp,string,CanonicalCategory,string,string,ClarificationAudience,string][]=[[/workday|supplier (registration|enrollment)|enroll.*supplier/i,'SUPPLIER_REGISTRATION','Registration','Registration','Supplier Registration','Internal Bid Team','Internal Bid Team'],[/(w-?9|w-?8|tax documentation|tax form)/i,'TAX_DOCUMENTATION','Administrative','Tax Documentation','Tax Documentation','Internal Bid Team','Internal Bid Team'],[/insurance/i,'INSURANCE_REQUIREMENTS','Insurance','Insurance','Insurance Requirements','Internal Bid Team','Legal/Compliance'],[/bond|bonding/i,'BONDING_REQUIREMENTS','Bonding','Bonding','Bonding Requirements','Internal Bid Team','Legal/Compliance'],[/deadline|due date|bid due|proposal due/i,'SUBMISSION_DEADLINE','Submission','Deadline','Submission Deadline','Buyer / Contracting Officer','Bid Lead'],[/submission method|submit|portal|email|physical delivery/i,'SUBMISSION_METHOD','Submission','Submission','Submission Method','Buyer / Contracting Officer','Bid Lead'],[/signature|signed/i,'AUTHORIZED_SIGNATURE','Administrative','Signature','Authorized Signature','Internal Bid Team','Bid Lead'],[/required form|bid form|forms/i,'REQUIRED_FORMS','Administrative','Forms','Required Forms','Internal Bid Team','Bid Lead'],[/email subject|subject line/i,'EMAIL_SUBJECT','Submission','Email','Required Email Subject','Buyer / Contracting Officer','Bid Lead'],[/attachment|file size/i,'ATTACHMENT_SIZE_LIMIT','Submission','Attachment','Attachment Size Limit','Buyer / Contracting Officer','Bid Lead'],[/addenda|addendum/i,'ADDENDA_ACKNOWLEDGEMENT','Administrative','Addenda','Addenda Acknowledgement','Internal Bid Team','Bid Lead'],[/fob destination/i,'FOB_DESTINATION','Commercial','FOB','FOB Destination','Buyer / Contracting Officer','Finance'],[/freight/i,'FREIGHT_INCLUDED','Commercial','Freight','Freight Included','Buyer / Contracting Officer','Finance'],[/delivery|lead time/i,'DELIVERY_LEAD_TIME','Delivery','Delivery','Delivery Lead Time','Supplier / Manufacturer','Operations'],[/manufacturer|model/i,'MANUFACTURER_MODEL_REQUIRED','Technical','Product','Manufacturer / Model Required','Supplier / Manufacturer','Technical'],[/technical|specification|piv/i,'TECHNICAL_COMPLIANCE','Technical','Technical','Technical Compliance','Supplier / Manufacturer','Technical'],[/installation/i,'INSTALLATION_REQUIRED','Technical','Installation','Installation Required','Supplier / Manufacturer','Operations'],[/training/i,'TRAINING_REQUIRED','Technical','Training','Training Required','Supplier / Manufacturer','Operations'],[/warranty/i,'WARRANTY_REQUIRED','Commercial','Warranty','Warranty Required','Supplier / Manufacturer','Sourcing']];
export function normalizeRequirementText(text:string){return text.toLowerCase().replace(/w\s*-\s*/g,'w-').replace(/[^a-z0-9]+/g,' ').replace(/\b(must|shall|required|requires|requirement|supplier|bidder|vendor|contractor|lsu)\b/g,' ').replace(/\s+/g,' ').trim()}
export function canonicalKeyFor(text:string,category?:string){for(const [re,key] of KNOWN) if(re.test(text)) return key; const normalized=normalizeRequirementText(`${category||'Other'} ${text}`).split(' ').slice(0,10).join('_').toUpperCase(); return `${String(category||'OTHER').toUpperCase()}_${normalized||'REQUIREMENT'}`.replace(/_+/g,'_')}
export function canonicalizeRequirements(analysis:BidAnalysis):CanonicalRequirement[]{const seed:CanonicalRequirement[]=[]; for(const item of analysis.complianceMatrix) seed.push(fromCompliance(item)); for(const rule of analysis.disqualificationRisks) seed.push(fromText(rule,'Disqualification Rule',true)); for(const req of analysis.mandatoryRequirements) seed.push(fromText(req,'Required',true)); return dedupeRequirements(seed)}
function fromCompliance(item:ComplianceItem):CanonicalRequirement{const key=canonicalKeyFor(`${item.category} ${item.requirement}`,item.category); const meta=metaForKey(key,item.requirement,item.category); return {id:key,canonicalKey:key,category:meta.category,requirementType:meta.type,title:meta.title,normalizedText:normalizeRequirementText(item.requirement),mandatory:item.mandatory,sourceEvidence:item.evidence?[item.evidence]:[],documentNames:item.documentName?[item.documentName]:[],pageNumbers:item.pageNumber?[item.pageNumber]:[],solicitationStatus:item.mandatory?'Required':'Optional',bidderStatus:bidderStatusFromCompliance(item.status),riskLevel:item.riskLevel,clarificationAudience:meta.audience,actionOwner:routeOwner(meta.owner,item),};}
function fromText(text:string,status:CanonicalRequirement['solicitationStatus'],mandatory:boolean):CanonicalRequirement{const key=canonicalKeyFor(text); const meta=metaForKey(key,text); return {id:key,canonicalKey:key,category:meta.category,requirementType:meta.type,title:meta.title,normalizedText:normalizeRequirementText(text),mandatory,sourceEvidence:[text],documentNames:[],pageNumbers:[],solicitationStatus:status,bidderStatus:'Unknown',riskLevel:status==='Disqualification Rule'?'High':'Medium',clarificationAudience:meta.audience,actionOwner:meta.owner};}
function metaForKey(key:string,text:string,category?:string){const row=KNOWN.find(([,known])=>known===key)||KNOWN.find(([re])=>re.test(text)); return row?{category:row[2],type:row[3],title:row[4],audience:row[5],owner:row[6]}:{category:(category as CanonicalCategory)||'Other',type:'Requirement',title:titleize(key),audience:'Internal Bid Team' as ClarificationAudience,owner:'Bid Lead'}}
function titleize(key:string){return key.toLowerCase().split('_').map(w=>w[0]?.toUpperCase()+w.slice(1)).join(' ')}
function bidderStatusFromCompliance(status:string):BidderStatus{if(status==='Compliant')return 'Confirmed Compliant'; if(status==='Not Compliant')return 'Confirmed Noncompliant'; if(status==='Needs Clarification')return 'Needs Clarification'; return 'Unknown'}
function routeOwner(owner:string,item:ComplianceItem){if(/buyer|contracting officer|co\b/i.test(item.owner))return owner; return item.owner||owner}
function riskRank(r:string){return r==='High'?3:r==='Medium'?2:1}
function statusRank(s:BidderStatus){return s==='Confirmed Noncompliant'?4:s==='Needs Clarification'?3:s==='Unknown'?2:s==='Confirmed Compliant'?1:0}
export function dedupeRequirements(items:CanonicalRequirement[]){const map=new Map<string,CanonicalRequirement>(); for(const item of items){const existing=map.get(item.canonicalKey); if(!existing){map.set(item.canonicalKey,{...item,id:item.canonicalKey}); continue} existing.mandatory=existing.mandatory||item.mandatory; existing.sourceEvidence=[...new Set([...existing.sourceEvidence,...item.sourceEvidence])]; existing.documentNames=[...new Set([...existing.documentNames,...item.documentNames])]; existing.pageNumbers=[...new Set([...existing.pageNumbers,...item.pageNumbers])].sort((a,b)=>a-b); if(riskRank(item.riskLevel)>riskRank(existing.riskLevel)) existing.riskLevel=item.riskLevel; if(statusRank(item.bidderStatus)>statusRank(existing.bidderStatus)) existing.bidderStatus=item.bidderStatus; if(existing.solicitationStatus!=='Required'&&item.solicitationStatus==='Required') existing.solicitationStatus='Required'; } return [...map.values()].sort((a,b)=>a.canonicalKey.localeCompare(b.canonicalKey))}
export function unresolvedRequirements(requirements:CanonicalRequirement[]){return requirements.filter(r=>r.mandatory&&(r.bidderStatus==='Unknown'||r.bidderStatus==='Needs Clarification'))}
export function activeHardStopsFromRequirements(requirements:CanonicalRequirement[]){return requirements.filter(r=>r.mandatory&&r.bidderStatus==='Confirmed Noncompliant').map(r=>`Confirmed mandatory noncompliance: ${r.title}`)}
export function complianceItemsFromCanonical(requirements:CanonicalRequirement[]):ComplianceItem[]{return requirements.filter(r=>r.solicitationStatus!=='Disqualification Rule').map(r=>({id:r.id,requirement:r.title,category:r.category==='Certification'?'Administrative':r.category,mandatory:r.mandatory,status:r.bidderStatus==='Confirmed Compliant'?'Compliant':r.bidderStatus==='Confirmed Noncompliant'?'Not Compliant':r.bidderStatus==='Needs Clarification'?'Needs Clarification':'Unknown',riskLevel:r.riskLevel,evidence:r.sourceEvidence[0]||'',documentName:r.documentNames[0],pageNumber:r.pageNumbers[0],actionNeeded:r.bidderStatus==='Confirmed Compliant'?'Prepare evidence for submission':`Resolve ${r.title}`,owner:r.actionOwner} as ComplianceItem))}
