import type { BidAnalysis, ComplianceItem, Confidence, Recommendation, Score } from '@/lib/types';
import { activeHardStopsFromRequirements, canonicalizeRequirements, complianceItemsFromCanonical, unresolvedRequirements, type CanonicalRequirement } from '../requirements/canonical';
export type DecisionInput={hardStops?:string[]; clarificationGates?:string[]; deadlineFeasibility?:number; technicalFit?:number; commercialFit?:number; complianceReadiness?:number; deliveryFeasibility?:number; pastPerformanceFit?:number; supplierReadiness?:number; knownCapabilityConflicts?:string[]; unknownMandatoryCapabilities?:string[]};
export const SCORE_WEIGHTS={technicalFit:0.25,complianceReadiness:0.20,commercialFit:0.15,deliveryFeasibility:0.15,supplierReadiness:0.10,pastPerformanceFit:0.05,deadlineFeasibility:0.10} as const;
const clamp=(n:number)=>Math.max(0,Math.min(100,Number.isFinite(n)?n:50)); const round=(n:number)=>Math.round(clamp(n));
export function applyDeterministicDecision(analysis:BidAnalysis):BidAnalysis{const copy=structuredClone(analysis) as BidAnalysis; copy.hardStops=Array.isArray(copy.hardStops)?copy.hardStops:[]; copy.disqualificationRisks=Array.isArray(copy.disqualificationRisks)?copy.disqualificationRisks:[]; copy.clarificationQuestions=Array.isArray(copy.clarificationQuestions)?copy.clarificationQuestions:[]; copy.clarificationGates=Array.isArray(copy.clarificationGates)?copy.clarificationGates:[]; copy.complianceMatrix=Array.isArray(copy.complianceMatrix)?copy.complianceMatrix:[]; copy.mandatoryRequirements=Array.isArray(copy.mandatoryRequirements)?copy.mandatoryRequirements:[]; const canonical=canonicalizeRequirements(copy); copy.canonicalRequirements=canonical; copy.complianceMatrix=complianceItemsFromCanonical(canonical).map(routeComplianceOwner); const taxonomy=classifyHardStops([...copy.hardStops,...activeHardStopsFromRequirements(canonical)],copy.disqualificationRisks); copy.hardStops=taxonomy.activeHardStops; copy.disqualificationRisks=taxonomy.disqualificationRisks; const scores=computeDimensionScores(copy,canonical); const overall=round(Object.entries(SCORE_WEIGHTS).reduce((sum,[key,weight])=>sum+(scores[key as keyof typeof scores].score*weight),0)); const confirmedFailure=hasConfirmedMandatoryFailure(copy); const unresolved=unresolvedRequirements(canonical); const hasClarification=unresolved.length>0||Object.values(scores).some(s=>s.confidence==='Needs Clarification'); const recommendation:Recommendation=copy.hardStops.length||confirmedFailure?'No Bid':overall>=70&&!hasClarification?'Bid':'Needs Clarification'; copy.subScores=scores; copy.opportunityScore={score:copy.hardStops.length||confirmedFailure?Math.min(overall,35):overall,confidence:copy.hardStops.length||confirmedFailure?'High':hasClarification?'Medium':'High',reasoning:decisionReasoning(recommendation,overall,copy.hardStops,hasClarification,confirmedFailure)}; copy.recommendation=recommendation; copy.recommendationReasoning=copy.opportunityScore.reasoning; copy.clarificationQuestions=dedupeClarifications(copy,canonical); copy.clarificationGates=dedupeGates(copy.clarificationGates,canonical); copy.positiveDrivers=overall>=70&&!copy.hardStops.length?[...new Set([...copy.positiveDrivers,'Deterministic scoring found no active hard stop.'])]:copy.positiveDrivers; copy.keyConcerns=[...new Set([...copy.keyConcerns,...copy.hardStops,...copy.clarificationGates])]; return copy;}
function computeDimensionScores(a:BidAnalysis,canonical:CanonicalRequirement[]):Record<string,Score>{
 const by=(category:string)=>canonical.filter(c=>c.category===category||c.title.toLowerCase().includes(category.toLowerCase()));
 return {
  technicalFit:scoreCanonicalDimension(by('Technical'),65,'Technical Fit','Confirmed technical requirements increase readiness; unknown technical capability is treated as Needs Review; confirmed mandatory technical noncompliance sharply reduces readiness.'),
  commercialFit:scoreFieldDimension([a.summary.paymentTerms,a.summary.priceValidity,a.summary.FOBTerms,a.summary.freightRequirements,a.summary.awardBasis],60,'Commercial Fit','Confirmed commercial terms and award basis increase readiness; missing or unclear pricing/payment/freight terms reduce readiness consistently.'),
  complianceReadiness:scoreCanonicalDimension(canonical.filter(c=>c.mandatory&&c.solicitationStatus!=='Disqualification Rule'),60,'Compliance Readiness','Mandatory compliance matrix states are converted deterministically: compliant helps, unknown/needs clarification reduces readiness, and confirmed noncompliance creates severe reduction.'),
  deliveryFeasibility:scoreFieldDimension([a.summary.deliveryRequirements,a.summary.deliveryLocations,a.summary.placeOfPerformance],60,'Delivery Feasibility','Confirmed delivery destinations/timing increase readiness; missing delivery evidence reduces readiness but is not an active hard stop by itself.'),
  pastPerformanceFit:mk(50,'Needs Clarification','Deterministic score 50: empty bidder profile means past performance is unknown; unknown bidder capability reduces confidence but is not noncompliance.'),
  supplierReadiness:scoreSupplierReadiness(canonical),
  deadlineFeasibility:deadlineScore(a.summary.dueDateTime.value)
 };}
function scoreCanonicalDimension(items:CanonicalRequirement[],emptyScore:number,label:string,reasoning:string){ const scored=items.filter(i=>i.bidderStatus!=='Not Applicable'); if(!scored.length)return mk(emptyScore,'Needs Clarification',`Deterministic score ${emptyScore}: no unique canonical ${label.toLowerCase()} requirements were identified after deduplication. ${reasoning}`); const counts=countCanonicalStates(scored); const weighted=scored.reduce((sum,item)=>sum+statePoints(item.bidderStatus)*(item.mandatory?1.5:1),0); const denom=scored.reduce((sum,item)=>sum+(item.mandatory?1.5:1),0); const score=round(weighted/denom); return mk(score,confidenceForScore(score),`Deterministic score ${score}: ${counts.confirmed} confirmed compliant, ${counts.unknown+counts.needsClarification} unknown/needs clarification, ${counts.noncompliant} confirmed noncompliant, ${counts.notApplicable} not applicable across ${scored.length} unique canonical requirement(s). ${reasoning}`)}
function scoreFieldDimension(fields:any[],emptyScore:number,label:string,reasoning:string){const counts=countFieldStates(fields); const total=counts.confirmed+counts.unknown+counts.noncompliant+counts.notApplicable; if(!total)return mk(emptyScore,'Needs Clarification',`Deterministic score ${emptyScore}: no ${label.toLowerCase()} evidence fields were available. ${reasoning}`); const score=round((counts.confirmed*80+counts.unknown*50+counts.notApplicable*70+counts.noncompliant*0)/total); return mk(score,confidenceForScore(score),`Deterministic score ${score}: ${counts.confirmed} confirmed evidence fields, ${counts.unknown} unknown/needs clarification, ${counts.noncompliant} confirmed conflicts, ${counts.notApplicable} not applicable. ${reasoning}`)}
function scoreSupplierReadiness(canonical:CanonicalRequirement[]){const supplierIssues=canonical.filter(r=>r.mandatory&&(r.bidderStatus==='Unknown'||r.bidderStatus==='Needs Clarification')&&(r.category==='Technical'||r.category==='Delivery'||r.clarificationAudience==='Supplier / Manufacturer'||r.actionOwner==='Supplier / Manufacturer')).length; const score=supplierIssues?45:60; return mk(score,supplierIssues?'Needs Clarification':'Medium',`Deterministic score ${score}: ${supplierIssues} supplier/manufacturer canonical readiness issue(s) remain. Empty supplier readiness is treated consistently as unknown, not noncompliant.`)}
function countCanonicalStates(items:CanonicalRequirement[]){return items.reduce((acc,item)=>{if(item.bidderStatus==='Confirmed Compliant')acc.confirmed++; else if(item.bidderStatus==='Confirmed Noncompliant')acc.noncompliant++; else if(item.bidderStatus==='Needs Clarification')acc.needsClarification++; else if(item.bidderStatus==='Not Applicable')acc.notApplicable++; else acc.unknown++; return acc},{confirmed:0,unknown:0,needsClarification:0,noncompliant:0,notApplicable:0})}
function statePoints(status:string){return status==='Confirmed Compliant'?100:status==='Confirmed Noncompliant'?0:status==='Needs Clarification'?55:status==='Not Applicable'?70:55}
function countFieldStates(fields:any[]){return fields.reduce((acc,field)=>{const state=normalizeFieldState(field); acc[state]+=1; return acc},{confirmed:0,unknown:0,noncompliant:0,notApplicable:0} as Record<'confirmed'|'unknown'|'noncompliant'|'notApplicable',number>)}
export function normalizeComplianceState(item:ComplianceItem){ if(!item.mandatory&&/not applicable|n\/a/i.test(`${item.status} ${item.requirement}`))return 'notApplicable' as const; if(item.status==='Compliant')return 'confirmed' as const; if(item.status==='Not Compliant')return 'noncompliant' as const; return 'unknown' as const;}
export function normalizeFieldState(field:any){ if(!field||field.status==='Not Found'||field.value==='Not Found')return 'unknown' as const; if(/not applicable|n\/a/i.test(String(field.value)))return 'notApplicable' as const; if(field.status==='Fact')return 'confirmed' as const; return 'unknown' as const;}
export function scoreQualityLabel(score:number){if(score<40)return 'Low'; if(score<70)return 'Medium'; if(score<85)return 'Good'; return 'High'}
function confidenceForScore(score:number):Confidence{return score<40?'Low':score<70?'Medium':'High'}
function deadlineScore(value:string){if(!value||value==='Not Found')return mk(45,'Needs Clarification','Deterministic score 45: bid deadline was not found; feasibility must be reviewed.'); const parsed=Date.parse(value); if(Number.isFinite(parsed)&&parsed<Date.now())return mk(0,'High','Deterministic score 0: bid deadline appears to have passed.'); return mk(80,'Medium','Deterministic score 80: bid deadline is identified; feasibility depends on remaining preparation time.');}
function mk(score:number,confidence:Confidence,reasoning:string):Score{return {score:round(score),confidence,reasoning}}
function hasConfirmedMandatoryFailure(a:BidAnalysis){return a.complianceMatrix.some(c=>c.mandatory&&c.status==='Not Compliant')}
export function classifyHardStops(hardStops:string[]=[],risks:string[]=[]){const active:string[]=[]; const rules=[...risks]; for(const item of hardStops){(isActiveHardStop(item)?active:rules).push(item)} return {activeHardStops:[...new Set(active)],disqualificationRisks:[...new Set(rules)]}}
function isActiveHardStop(text:string){const t=text.toLowerCase(); if(/deadline (has )?passed|confirmed bidder (cannot|can't|is unable)|bidder explicitly confirms|bidder (cannot|can't|is unable) (meet|obtain|complete|satisfy)|confirmed inability|confirmed mandatory .* (noncompliance|non-compliance|conflict)|confirmed .* does not meet/i.test(t))return true; if(/unknown|needs clarification|can be completed|can be confirmed|confirm |verify |do not submit unless|failure to|may result|must |required |shall |if /i.test(text))return false; return false}
export function routeComplianceOwner(item:ComplianceItem):ComplianceItem{let owner=item.owner; if(/buyer|contracting officer|co\b/i.test(owner)){ if(item.category==='Technical'||/manufacturer|model|supplier/i.test(item.requirement)) owner='Supplier / Manufacturer'; else if(item.category==='Insurance'||item.category==='Legal'||item.category==='Bonding') owner='Internal Bid Team'; else owner='Internal Bid Team'; } return {...item,owner};}

function dedupeClarifications(a:BidAnalysis,canonical:CanonicalRequirement[]){const byKey=new Map<string,any>(); for(const q of a.clarificationQuestions.filter(Boolean)){const key=String(q.relatedRequirement||'').match(/^[A-Z0-9_]+$/)?String(q.relatedRequirement):canonicalizeQuestionKey(q.question||''); const normalized={...q,relatedRequirement:key,audience:routeClarificationAudience(q.question,key,canonical)}; if(isGenericBuyerReadiness(normalized)) normalized.audience='Internal Bid Team'; const mapKey=`${key}:${normalized.audience}`; byKey.set(mapKey,preferQuestion(byKey.get(mapKey),normalized));} for(const r of unresolvedRequirements(canonical)){const q=questionForRequirement(r); const mapKey=`${r.canonicalKey}:${q.audience}`; if(!byKey.has(mapKey)) byKey.set(mapKey,q);} return [...byKey.values()].filter(q=>String(q.question||'').trim()).sort((a,b)=>`${a.relatedRequirement}:${a.audience}`.localeCompare(`${b.relatedRequirement}:${b.audience}`))}

function dedupeGates(existing:string[]=[],canonical:CanonicalRequirement[]){const gates=new Map<string,string>(); for(const gate of existing.map(cleanGate).filter(Boolean)){const key=canonicalizeQuestionKey(gate); gates.set(key,preferSpecific(gates.get(key),gate));} for(const r of unresolvedRequirements(canonical)){const gate=gateForRequirement(r); gates.set(r.canonicalKey,preferSpecific(gates.get(r.canonicalKey),gate));} return [...gates.values()].sort()}
function preferSpecific(current:string|undefined,next:string){if(!current)return next; if(/^Confirm readiness for/i.test(current)&&!/^Confirm readiness for/i.test(next))return next; return current}
function cleanGate(gate:string){return String(gate||'').replace(/^Resolve\s+/i,'Confirm readiness for ').replace(/Other Other|Commercial Commercial/gi,'').replace(/\s+/g,' ').trim()}
function gateForRequirement(r:CanonicalRequirement){if(r.canonicalKey==='SUPPLIER_REGISTRATION'||r.canonicalKey==='TAX_DOCUMENTATION')return 'Confirm LSU Workday enrollment and tax-document readiness.'; if(r.canonicalKey==='SUBMISSION_DEADLINE')return 'Confirm the bid team can complete and submit before the deadline.'; if(r.canonicalKey==='SUBMISSION_METHOD')return 'Confirm the bid package can be submitted using the required electronic submission method.'; if(r.canonicalKey==='AUTHORIZED_SIGNATURE')return 'Confirm an authorized signatory is available and required forms can be signed.'; if(r.canonicalKey==='FOB_DESTINATION_PRICING')return 'Confirm pricing can be submitted FOB Destination with required delivery charges included.'; if(r.canonicalKey==='TECHNICAL_COMPLIANCE')return 'Confirm the proposed technical solution meets all mandatory technical thresholds.'; if(r.canonicalKey==='LASER_SAFETY_COMPLIANCE')return 'Confirm laser safety compliance documentation is available.'; if(r.canonicalKey==='INSTALLATION_REQUIRED')return 'Confirm installation services can be provided as required.'; if(r.canonicalKey==='TRAINING_REQUIRED')return 'Confirm training services can be provided as required.'; if(r.category==='Technical')return 'Confirm proposed technical solution meets all mandatory thresholds.'; if(r.canonicalKey==='INSURANCE_REQUIREMENTS')return 'Confirm insurance requirements and bidder insurance capability.'; return `Confirm readiness for ${r.title}.`}
function questionForRequirement(r:CanonicalRequirement){const audience=audienceForRequirement(r); return {question:questionText(r,audience),whyItMatters:`${r.title} is a ${r.mandatory?'mandatory':'tracked'} requirement with bidder status ${r.bidderStatus}.`,relatedRequirement:r.canonicalKey,priority:r.riskLevel,audience}}
function audienceForRequirement(r:CanonicalRequirement){const evidence=r.sourceEvidence.join(' ').toLowerCase(); if(/\b(ct|cst|cdt|timezone|time zone|daylight saving|daylight-saving)\b/i.test(evidence)&&/(ambiguous|unclear|conflict|contradict|interpret|inquiry deadline|business days?)/i.test(evidence))return 'Buyer / Contracting Officer' as const; if(/inquir(y|ies).*business days?|questions?.*business days?/i.test(evidence))return 'Buyer / Contracting Officer' as const; if(r.canonicalKey==='AUTHORIZED_SIGNATURE') return /electronic.*(original )?signature|original signature.*electronic|signature format.*(ambiguous|unclear|conflict)|signature.*(ambiguous|unclear|conflict)/i.test(evidence)?'Buyer / Contracting Officer' as const:'Internal Bid Team' as const; if(r.canonicalKey==='AWARD_BASIS'&&/(conflict|contradict|ambiguous|unclear|all[- ]or[- ]none|separate.*grouped)/i.test(evidence))return 'Buyer / Contracting Officer' as const; if((/missing|not provided|unclear|ambiguous|conflict|contradict|referenced attachment|attachment not included|addenda missing|insurance attachment|insurance limits/i.test(evidence))&&!/bidder status|readiness|can we|confirm readiness|capability/i.test(evidence))return 'Buyer / Contracting Officer' as const; if(r.category==='Technical'||r.category==='Delivery'||r.clarificationAudience==='Supplier / Manufacturer')return 'Supplier / Manufacturer' as const; return 'Internal Bid Team' as const}
function questionText(r:CanonicalRequirement,audience:string){if(audience==='Buyer / Contracting Officer'){ if(r.canonicalKey==='AWARD_BASIS')return 'Please confirm whether this solicitation will be awarded strictly on an all-or-none basis or whether the standard provision allowing separate or grouped awards applies.'; if(r.canonicalKey==='INSURANCE_REQUIREMENTS')return 'Please provide the referenced insurance requirements, including required coverage limits, endorsements, and certificate requirements.'; if(r.canonicalKey==='SUBMISSION_DEADLINE')return 'Please confirm the official deadline interpretation, including CT/CST timezone handling and any relative inquiry-deadline calculation.'; return `Please clarify ${r.title.toLowerCase()} because the solicitation evidence appears missing, ambiguous, or conflicting.`;} if(audience==='Supplier / Manufacturer')return `Confirm supplier/manufacturer capability for ${r.title}.`; if(r.canonicalKey==='SUBMISSION_DEADLINE')return 'Confirm the bid team can meet the submission deadline.'; if(r.canonicalKey==='SUBMISSION_METHOD')return 'Confirm the bid team can use the required submission method.'; if(r.canonicalKey==='SUPPLIER_REGISTRATION'||r.canonicalKey==='TAX_DOCUMENTATION')return 'Confirm LSU Workday enrollment and W-9/W-8 readiness.'; return `Confirm internal readiness for ${r.title}.`}
function preferQuestion(current:any|undefined,next:any){if(!current)return next; const currentGeneric=/confirm supplier\/manufacturer capability for|confirm internal readiness for|confirm readiness for/i.test(String(current.question)); const nextGeneric=/confirm supplier\/manufacturer capability for|confirm internal readiness for|confirm readiness for/i.test(String(next.question)); return currentGeneric&&!nextGeneric?next:current}
function isGenericBuyerReadiness(q:any){return q.audience==='Buyer / Contracting Officer'&&/confirm readiness|can we|bid team|internal readiness/i.test(`${q.question} ${q.whyItMatters}`)}
function routeClarificationAudience(question:string,key:string,canonical:CanonicalRequirement[]){const q=String(question||'').toLowerCase(); if(/(exact calendar date|official calculated date|written inquiry deadline|questions?.*business days?|inquir(y|ies).*business days?|ct\/cst|ct vs cst|cst.*ct|timezone|time zone)/i.test(q))return 'Buyer / Contracting Officer'; if(/insurance/i.test(q)&&/(please provide|referenced|attached|attachment|coverage limits|endorsements|certificate requirements|official limits|missing)/i.test(q)&&!/capability|can (we|the bidder)|readiness/i.test(q))return 'Buyer / Contracting Officer'; if(/redacted copy/i.test(q)&&/(specific format|content|buyer require|does the buyer|unclear|clarify|guidance)/i.test(q))return 'Buyer / Contracting Officer'; if(/(supplier|manufacturer).*(provide|capability|can).*(installation|training)|onsite installation.*training/i.test(q))return 'Supplier / Manufacturer'; const r=canonical.find(c=>c.canonicalKey===key); if(!r)return /technical|manufacturer|model|supplier capability|installation|training/i.test(question)?'Supplier / Manufacturer':/missing|unclear|ambiguous|contradict|attachment/i.test(question)?'Buyer / Contracting Officer':'Internal Bid Team'; return audienceForRequirement(r)}

function canonicalizeQuestionKey(text:string){return canonicalizeRequirements({complianceMatrix:[{id:'q',requirement:text,category:'Administrative',mandatory:true,status:'Unknown',riskLevel:'Medium',evidence:'',actionNeeded:'',owner:'Internal Bid Team'}],disqualificationRisks:[],mandatoryRequirements:[]} as unknown as BidAnalysis)[0]?.canonicalKey||text}
function decisionReasoning(rec:Recommendation,score:number,hardStops:string[],hasClarification:boolean,confirmedFailure:boolean){if(rec==='No Bid')return `No Bid is deterministic because ${hardStops.length?'active hard stop(s) are present':'a confirmed mandatory compliance failure is present'}. Overall readiness before hard-stop cap: ${score}/100.`; if(rec==='Bid')return `Bid is deterministic because the weighted score is ${score}/100 with no active hard stops or unresolved clarification gates.`; return `Needs Review because the deterministic weighted score is ${score}/100${hasClarification?' and unresolved clarification gates or unknown readiness items remain':''}. Unknowns reduce confidence but are not treated as active hard stops.`}
export function scoreBidReadiness(input:DecisionInput){const hardStops=[...(input.hardStops||[]),...(input.knownCapabilityConflicts||[])]; const clarificationGates=[...(input.clarificationGates||[]),...(input.unknownMandatoryCapabilities||[])]; const subScores={technicalFit:mk(input.technicalFit??50,input.technicalFit==null?'Needs Clarification':'Medium','Technical requirements fit known capabilities where evidence exists.'),commercialFit:mk(input.commercialFit??50,input.commercialFit==null?'Needs Clarification':'Medium','Pricing and payment terms appear commercially workable where known.'),complianceReadiness:mk(input.complianceReadiness??50,input.complianceReadiness==null?'Needs Clarification':'Medium','Mandatory compliance readiness based on known requirements.'),deliveryFeasibility:mk(input.deliveryFeasibility??50,input.deliveryFeasibility==null?'Needs Clarification':'Medium','Delivery timing and locations compared with known capability.'),pastPerformanceFit:mk(input.pastPerformanceFit??50,input.pastPerformanceFit==null?'Needs Clarification':'Medium','Past performance fit is scored only when known.'),supplierReadiness:mk(input.supplierReadiness??50,input.supplierReadiness==null?'Needs Clarification':'Medium','Supplier availability and authorization readiness where known.'),deadlineFeasibility:mk(input.deadlineFeasibility??50,input.deadlineFeasibility==null?'Needs Clarification':'Medium','Deadline feasibility based on remaining time and submission burden.')}; const avg=round(Object.entries(SCORE_WEIGHTS).reduce((sum,[k,w])=>sum+subScores[k as keyof typeof subScores].score*w,0)); const recommendation:Recommendation=hardStops.length?'No Bid':clarificationGates.length?'Needs Clarification':'Bid'; return {recommendation,opportunityScore:{score:hardStops.length?Math.min(avg,35):avg,confidence:hardStops.length?'High':clarificationGates.length?'Medium':'High',reasoning:decisionReasoning(recommendation,avg,hardStops,!!clarificationGates.length,!!hardStops.length)},subScores,hardStops,clarificationGates,positiveDrivers:avg>=70&&!hardStops.length?['No deterministic hard stop identified.']:[],keyConcerns:[...hardStops,...clarificationGates]};}
export function decideBidFit(input:DecisionInput):Recommendation{return scoreBidReadiness(input).recommendation}
