import type { BidAnalysis, ComplianceItem, Confidence, Recommendation, Score } from '@/lib/types';
export type DecisionInput={hardStops?:string[]; clarificationGates?:string[]; deadlineFeasibility?:number; technicalFit?:number; commercialFit?:number; complianceReadiness?:number; deliveryFeasibility?:number; pastPerformanceFit?:number; supplierReadiness?:number; knownCapabilityConflicts?:string[]; unknownMandatoryCapabilities?:string[]};
export const SCORE_WEIGHTS={technicalFit:0.20,commercialFit:0.12,complianceReadiness:0.20,deliveryFeasibility:0.15,pastPerformanceFit:0.10,supplierReadiness:0.10,deadlineFeasibility:0.13} as const;
const clamp=(n:number)=>Math.max(0,Math.min(100,Number.isFinite(n)?n:50)); const round=(n:number)=>Math.round(clamp(n));
export function applyDeterministicDecision(analysis:BidAnalysis):BidAnalysis{const copy=structuredClone(analysis) as BidAnalysis; const taxonomy=classifyHardStops(copy.hardStops,copy.disqualificationRisks); copy.hardStops=taxonomy.activeHardStops; copy.disqualificationRisks=taxonomy.disqualificationRisks; copy.complianceMatrix=copy.complianceMatrix.map(routeComplianceOwner); const scores=computeDimensionScores(copy); const overall=round(Object.entries(SCORE_WEIGHTS).reduce((sum,[key,weight])=>sum+(scores[key as keyof typeof scores].score*weight),0)); const confirmedFailure=hasConfirmedMandatoryFailure(copy); const hasClarification=copy.clarificationGates.some(Boolean)||copy.clarificationQuestions.length>0||Object.values(scores).some(s=>s.confidence==='Needs Clarification'); const recommendation:Recommendation=copy.hardStops.length||confirmedFailure?'No Bid':overall>=70&&!hasClarification?'Bid':'Needs Clarification'; copy.subScores=scores; copy.opportunityScore={score:copy.hardStops.length||confirmedFailure?Math.min(overall,35):overall,confidence:copy.hardStops.length||confirmedFailure?'High':hasClarification?'Medium':'High',reasoning:decisionReasoning(recommendation,overall,copy.hardStops,hasClarification,confirmedFailure)}; copy.recommendation=recommendation; copy.recommendationReasoning=copy.opportunityScore.reasoning; copy.positiveDrivers=overall>=70&&!copy.hardStops.length?[...new Set([...copy.positiveDrivers,'Deterministic scoring found no active hard stop.'])]:copy.positiveDrivers; copy.keyConcerns=[...new Set([...copy.keyConcerns,...copy.hardStops,...copy.clarificationGates])]; return copy;}
function computeDimensionScores(a:BidAnalysis):Record<string,Score>{
 const by=(category:string)=>a.complianceMatrix.filter(c=>c.category===category||c.requirement.toLowerCase().includes(category.toLowerCase()));
 return {
  technicalFit:scoreComplianceDimension(by('Technical'),65,'Technical Fit','Confirmed technical requirements increase readiness; unknown technical capability is treated as Needs Review; confirmed mandatory technical noncompliance sharply reduces readiness.'),
  commercialFit:scoreFieldDimension([a.summary.paymentTerms,a.summary.priceValidity,a.summary.FOBTerms,a.summary.freightRequirements,a.summary.awardBasis],60,'Commercial Fit','Confirmed commercial terms and award basis increase readiness; missing or unclear pricing/payment/freight terms reduce readiness consistently.'),
  complianceReadiness:scoreComplianceDimension(a.complianceMatrix.filter(c=>c.mandatory),60,'Compliance Readiness','Mandatory compliance matrix states are converted deterministically: compliant helps, unknown/needs clarification reduces readiness, and confirmed noncompliance creates severe reduction.'),
  deliveryFeasibility:scoreFieldDimension([a.summary.deliveryRequirements,a.summary.deliveryLocations,a.summary.placeOfPerformance],60,'Delivery Feasibility','Confirmed delivery destinations/timing increase readiness; missing delivery evidence reduces readiness but is not an active hard stop by itself.'),
  pastPerformanceFit:mk(50,'Needs Clarification','Deterministic score 50: empty bidder profile means past performance is unknown; unknown bidder capability reduces confidence but is not noncompliance.'),
  supplierReadiness:scoreSupplierReadiness(a),
  deadlineFeasibility:deadlineScore(a.summary.dueDateTime.value)
 };}
function scoreComplianceDimension(items:ComplianceItem[],emptyScore:number,label:string,reasoning:string){ if(!items.length)return mk(emptyScore,'Needs Clarification',`Deterministic score ${emptyScore}: no ${label.toLowerCase()} compliance items were identified. ${reasoning}`); const counts=countStates(items); const score=round((counts.confirmed*100+counts.unknown*55+counts.notApplicable*70+counts.noncompliant*0)/items.length); return mk(score,confidenceForScore(score),`Deterministic score ${score}: ${counts.confirmed} confirmed, ${counts.unknown} unknown/needs clarification, ${counts.noncompliant} confirmed noncompliant, ${counts.notApplicable} not applicable. ${reasoning}`)}
function scoreFieldDimension(fields:any[],emptyScore:number,label:string,reasoning:string){const counts=countFieldStates(fields); const total=counts.confirmed+counts.unknown+counts.noncompliant+counts.notApplicable; if(!total)return mk(emptyScore,'Needs Clarification',`Deterministic score ${emptyScore}: no ${label.toLowerCase()} evidence fields were available. ${reasoning}`); const score=round((counts.confirmed*80+counts.unknown*50+counts.notApplicable*70+counts.noncompliant*0)/total); return mk(score,confidenceForScore(score),`Deterministic score ${score}: ${counts.confirmed} confirmed evidence fields, ${counts.unknown} unknown/needs clarification, ${counts.noncompliant} confirmed conflicts, ${counts.notApplicable} not applicable. ${reasoning}`)}
function scoreSupplierReadiness(a:BidAnalysis){const supplierQuestions=a.clarificationQuestions.filter(q=>q.audience==='Supplier / Manufacturer').length; const score=supplierQuestions?45:60; return mk(score,supplierQuestions?'Needs Clarification':'Medium',`Deterministic score ${score}: ${supplierQuestions} supplier/manufacturer clarification question(s) remain. Empty supplier readiness is treated consistently as unknown, not noncompliant.`)}
function countStates(items:ComplianceItem[]){return items.reduce((acc,item)=>{const state=normalizeComplianceState(item); acc[state]+=1; return acc},{confirmed:0,unknown:0,noncompliant:0,notApplicable:0} as Record<'confirmed'|'unknown'|'noncompliant'|'notApplicable',number>)}
function countFieldStates(fields:any[]){return fields.reduce((acc,field)=>{const state=normalizeFieldState(field); acc[state]+=1; return acc},{confirmed:0,unknown:0,noncompliant:0,notApplicable:0} as Record<'confirmed'|'unknown'|'noncompliant'|'notApplicable',number>)}
export function normalizeComplianceState(item:ComplianceItem){ if(!item.mandatory&&/not applicable|n\/a/i.test(`${item.status} ${item.requirement}`))return 'notApplicable' as const; if(item.status==='Compliant')return 'confirmed' as const; if(item.status==='Not Compliant')return 'noncompliant' as const; return 'unknown' as const;}
export function normalizeFieldState(field:any){ if(!field||field.status==='Not Found'||field.value==='Not Found')return 'unknown' as const; if(/not applicable|n\/a/i.test(String(field.value)))return 'notApplicable' as const; if(field.status==='Fact')return 'confirmed' as const; return 'unknown' as const;}
export function scoreQualityLabel(score:number){if(score<40)return 'Low'; if(score<70)return 'Medium'; if(score<85)return 'Good'; return 'High'}
function confidenceForScore(score:number):Confidence{return score<40?'Low':score<70?'Medium':'High'}
function deadlineScore(value:string){if(!value||value==='Not Found')return mk(45,'Needs Clarification','Deterministic score 45: bid deadline was not found; feasibility must be reviewed.'); const parsed=Date.parse(value); if(Number.isFinite(parsed)&&parsed<Date.now())return mk(0,'High','Deterministic score 0: bid deadline appears to have passed.'); return mk(80,'Medium','Deterministic score 80: bid deadline is identified; feasibility depends on remaining preparation time.');}
function mk(score:number,confidence:Confidence,reasoning:string):Score{return {score:round(score),confidence,reasoning}}
function hasConfirmedMandatoryFailure(a:BidAnalysis){return a.complianceMatrix.some(c=>c.mandatory&&c.status==='Not Compliant')}
export function classifyHardStops(hardStops:string[]=[],risks:string[]=[]){const active:string[]=[]; const rules=[...risks]; for(const item of hardStops){(isActiveHardStop(item)?active:rules).push(item)} return {activeHardStops:[...new Set(active)],disqualificationRisks:[...new Set(rules)]}}
function isActiveHardStop(text:string){const t=text.toLowerCase(); if(/deadline (has )?passed|confirmed bidder (cannot|can't|is unable)|bidder explicitly confirms|bidder (cannot|can't|is unable) (meet|obtain|complete|satisfy)|confirmed inability|confirmed mandatory .* (noncompliance|non-compliance|conflict)|confirmed .* does not meet/i.test(t))return true; if(/unknown|needs clarification|can be completed|can be confirmed|confirm |verify |do not submit unless|failure to|may result|must |required |shall |if /i.test(text))return false; return false}
export function routeComplianceOwner(item:ComplianceItem):ComplianceItem{let owner=item.owner; if(/buyer|contracting officer|co\b/i.test(owner)){ if(item.category==='Technical'||/manufacturer|model|supplier/i.test(item.requirement)) owner='Supplier / Manufacturer'; else if(item.category==='Insurance'||item.category==='Legal'||item.category==='Bonding') owner='Legal/Compliance'; else owner='Internal Bid Team'; } return {...item,owner};}
function decisionReasoning(rec:Recommendation,score:number,hardStops:string[],hasClarification:boolean,confirmedFailure:boolean){if(rec==='No Bid')return `No Bid is deterministic because ${hardStops.length?'active hard stop(s) are present':'a confirmed mandatory compliance failure is present'}. Overall readiness before hard-stop cap: ${score}/100.`; if(rec==='Bid')return `Bid is deterministic because the weighted score is ${score}/100 with no active hard stops or unresolved clarification gates.`; return `Needs Review because the deterministic weighted score is ${score}/100${hasClarification?' and unresolved clarification gates or unknown readiness items remain':''}. Unknowns reduce confidence but are not treated as active hard stops.`}
export function scoreBidReadiness(input:DecisionInput){const hardStops=[...(input.hardStops||[]),...(input.knownCapabilityConflicts||[])]; const clarificationGates=[...(input.clarificationGates||[]),...(input.unknownMandatoryCapabilities||[])]; const subScores={technicalFit:mk(input.technicalFit??50,input.technicalFit==null?'Needs Clarification':'Medium','Technical requirements fit known capabilities where evidence exists.'),commercialFit:mk(input.commercialFit??50,input.commercialFit==null?'Needs Clarification':'Medium','Pricing and payment terms appear commercially workable where known.'),complianceReadiness:mk(input.complianceReadiness??50,input.complianceReadiness==null?'Needs Clarification':'Medium','Mandatory compliance readiness based on known requirements.'),deliveryFeasibility:mk(input.deliveryFeasibility??50,input.deliveryFeasibility==null?'Needs Clarification':'Medium','Delivery timing and locations compared with known capability.'),pastPerformanceFit:mk(input.pastPerformanceFit??50,input.pastPerformanceFit==null?'Needs Clarification':'Medium','Past performance fit is scored only when known.'),supplierReadiness:mk(input.supplierReadiness??50,input.supplierReadiness==null?'Needs Clarification':'Medium','Supplier availability and authorization readiness where known.'),deadlineFeasibility:mk(input.deadlineFeasibility??50,input.deadlineFeasibility==null?'Needs Clarification':'Medium','Deadline feasibility based on remaining time and submission burden.')}; const avg=round(Object.entries(SCORE_WEIGHTS).reduce((sum,[k,w])=>sum+subScores[k as keyof typeof subScores].score*w,0)); const recommendation:Recommendation=hardStops.length?'No Bid':clarificationGates.length?'Needs Clarification':'Bid'; return {recommendation,opportunityScore:{score:hardStops.length?Math.min(avg,35):avg,confidence:hardStops.length?'High':clarificationGates.length?'Medium':'High',reasoning:decisionReasoning(recommendation,avg,hardStops,!!clarificationGates.length,!!hardStops.length)},subScores,hardStops,clarificationGates,positiveDrivers:avg>=70&&!hardStops.length?['No deterministic hard stop identified.']:[],keyConcerns:[...hardStops,...clarificationGates]};}
export function decideBidFit(input:DecisionInput):Recommendation{return scoreBidReadiness(input).recommendation}
