import type { Confidence, Recommendation, Score } from '@/lib/types';
export type DecisionInput={hardStops?:string[]; clarificationGates?:string[]; deadlineFeasibility?:number; technicalFit?:number; commercialFit?:number; complianceReadiness?:number; deliveryFeasibility?:number; pastPerformanceFit?:number; supplierReadiness?:number; knownCapabilityConflicts?:string[]; unknownMandatoryCapabilities?:string[]};
const clamp=(n:number)=>Math.max(0,Math.min(100,Number.isFinite(n)?n:50));
export function scoreBidReadiness(input:DecisionInput):{recommendation:Recommendation; opportunityScore:Score; subScores:Record<string,Score>; hardStops:string[]; clarificationGates:string[]; positiveDrivers:string[]; keyConcerns:string[]}{
 const hardStops=[...(input.hardStops||[]),...(input.knownCapabilityConflicts||[])]; const clarificationGates=[...(input.clarificationGates||[]),...(input.unknownMandatoryCapabilities||[])];
 const subScores={technicalFit:mk(input.technicalFit,'Technical requirements fit known capabilities where evidence exists.'),commercialFit:mk(input.commercialFit,'Pricing and payment terms appear commercially workable where known.'),complianceReadiness:mk(input.complianceReadiness,'Mandatory compliance readiness based on known requirements.'),deliveryFeasibility:mk(input.deliveryFeasibility,'Delivery timing and locations compared with known capability.'),pastPerformanceFit:mk(input.pastPerformanceFit,'Past performance fit is scored only when known.'),supplierReadiness:mk(input.supplierReadiness,'Supplier availability and authorization readiness where known.'),deadlineFeasibility:mk(input.deadlineFeasibility,'Deadline feasibility based on remaining time and submission burden.')};
 const avg=Object.values(subScores).reduce((a,s)=>a+s.score,0)/Object.keys(subScores).length; const unknownPenalty=Math.min(20,clarificationGates.length*4); const hardPenalty=hardStops.length?60:0; const finalScore=clamp(avg-unknownPenalty-hardPenalty); const recommendation:Recommendation=hardStops.length?'No Bid':clarificationGates.length?'Needs Clarification':'Bid';
 return {recommendation,opportunityScore:{score:finalScore,confidence:hardStops.length?'High':clarificationGates.length?'Medium':'High',reasoning:hardStops.length?'No Bid is enforced only because documented non-remediable hard stop(s) exist.':clarificationGates.length?'Needs Clarification because mandatory capability or solicitation facts remain unknown/ambiguous.':'No hard stops or mandatory unknowns were identified by deterministic decision rules.'},subScores,hardStops,clarificationGates,positiveDrivers:finalScore>=70&&!hardStops.length?['No deterministic hard stop identified.']:[],keyConcerns:[...hardStops,...clarificationGates]}; }
export function decideBidFit(input:DecisionInput):Recommendation{return scoreBidReadiness(input).recommendation}
function mk(value:number|undefined,reasoning:string):Score{const unknown=value==null; return {score:clamp(value??50),confidence:(unknown?'Needs Clarification':'Medium') as Confidence,reasoning:unknown?`${reasoning} Capability or requirement information is unknown.`:reasoning}}
